CREATE OR ALTER PROCEDURE [dbo].[sp_Workflow_GetByName]
	@WORKFLOW_NAME  	VARCHAR(255)
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	
	SET @QUERY = 'SELECT 
									CAST(W.WORKFLOW_ID AS INT) AS WORKFLOW_ID,
									H.WORKFLOW_CODE,
									H.WORKFLOW_NAME,
									CAST(W.WORKFLOW_SEQ AS INT) AS WORKFLOW_SEQ,
									W.APPROVER,
									U.FULL_NAME AS APPROVER_NAME,
									W.CREATED_DT,
									W.CREATED_BY,
									W.CHANGED_DT,
									W.CHANGED_BY
								FROM [dbo].[TB_M_WORKFLOW_D] W
								JOIN [dbo].[TB_M_WORKFLOW_H] H ON H.WORKFLOW_ID = W.WORKFLOW_ID
								JOIN [dbo].[TB_M_USER] U ON W.APPROVER = U.USERNAME
								WHERE 1 = 1 '
								
	IF @WORKFLOW_NAME IS NOT NULL
	BEGIN
		SET @QUERY += ' AND H.WORKFLOW_NAME LIKE ''' + REPLACE(@WORKFLOW_NAME , '*', '%') + ''' '
	END
	
	SET @QUERY += ' ORDER BY W.WORKFLOW_SEQ ASC'
	
	EXEC(@QUERY)
	
END
GO
