CREATE OR ALTER PROCEDURE [dbo].[sp_Workflow_Create]
	@WORKFLOW_NAME 	VARCHAR(255),
	@LOGIN_USER 		VARCHAR(255),
	@RETURN_MSG 		VARCHAR(MAX) OUTPUT,
	@RETURN_ID	 		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	
	INSERT INTO [dbo].[TB_R_APPROVAL_H] (
		[APPROVAL_DATE],
		[APPROVAL_STATUS],
		[CURRENT_SEQ],
		[CREATOR],
		[CREATED_BY],
		[CREATED_DT]
	) 
	VALUES (
		GETDATE(),
		0,
		1,
		@LOGIN_USER,
		@LOGIN_USER,
		GETDATE()
	)
	
	IF @@ROWCOUNT > 0 
	BEGIN
		DECLARE @approvalId INT;
		SET @approvalId = SCOPE_IDENTITY();
		
		INSERT INTO [dbo].[TB_R_APPROVAL_D] (
			[APPROVAL_ID],
			[WORKFLOW_SEQ],
			[APPROVER],
			[STATUS],
			[REMARK],
			[CREATED_BY],
			[CREATED_DT]
		) 
		SELECT 
			@approvalId,
			D.[WORKFLOW_SEQ],
			D.[APPROVER],
			0,
			NULL,
			@LOGIN_USER,
			GETDATE()
		FROM [TB_M_WORKFLOW_D] D
		JOIN [TB_M_WORKFLOW_H] H ON H.[WORKFLOW_ID] = D.[WORKFLOW_ID]
		WHERE H.[WORKFLOW_NAME] = @WORKFLOW_NAME
			
		SET @RETURN_ID = @approvalId;
		SET @RETURN_MSG = 'Successfully Create Workflow ' + @WORKFLOW_NAME
		RETURN 1;
		
	END
	ELSE BEGIN
		
		SET @RETURN_MSG = 'ERROR: Create Workflow ' + @WORKFLOW_NAME
		RETURN 0;
	
	END
	
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
