CREATE OR ALTER PROCEDURE [dbo].[sp_Workflow_InsertHeader]
  @WORKFLOW_CODE 	VARCHAR(50),
	@WORKFLOW_NAME 	VARCHAR(255),
	@LOGIN_USER 		VARCHAR(255),
	@RETURN_MSG 		VARCHAR(MAX) OUTPUT,
	@RETURN_ID			INT OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Workflow_InsertHeader';
	
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Workflow Header', 'Insert', @LOCATION, @LOGIN_USER

	IF @WORKFLOW_CODE IS NULL OR LEN(@WORKFLOW_CODE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Workflow Code should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @WORKFLOW_NAME IS NULL OR LEN(@WORKFLOW_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Workflow Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		SET @RETURN_ID = 0;
		RETURN 0;
	END	
	
	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_WORKFLOW_H] WHERE WORKFLOW_CODE = @WORKFLOW_CODE)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Workflow already exist. (Workflow Code: "' + @WORKFLOW_CODE+ '")';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		SET @RETURN_ID = 0;
		RETURN 0;
	END
	
	INSERT INTO [dbo].[TB_M_WORKFLOW_H] (
		WORKFLOW_CODE,
		WORKFLOW_NAME,
		CREATED_DT,
		CREATED_BY,
		CHANGED_DT,
		CHANGED_BY
	) VALUES (
		@WORKFLOW_CODE,
		@WORKFLOW_NAME,
		GETDATE(),
		@LOGIN_USER,
		GETDATE(),
		@LOGIN_USER
	)
	
	IF @@ROWCOUNT > 0 
	BEGIN
		DECLARE @workflowId INT;
		SET @workflowId = SCOPE_IDENTITY();
		
		SET @RETURN_ID = @workflowId;
	END
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
	
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
