CREATE OR ALTER PROCEDURE [dbo].[sp_Workflow_InsertDetail]
	@WORKFLOW_ID		INT,
	@WORKFLOW_SEQ 	INT,
	@APPROVER 			VARCHAR(50),
	@LOGIN_USER 		VARCHAR(255),
	@RETURN_MSG 		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Workflow_InsertDetail';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Workflow Detail', 'Insert', @LOCATION, @LOGIN_USER

	IF @WORKFLOW_ID IS NULL OR LEN(@WORKFLOW_ID) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Workflow ID should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @WORKFLOW_SEQ IS NULL OR LEN(@WORKFLOW_SEQ) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Sequence should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @APPROVER IS NULL OR LEN(@APPROVER) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Approver should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	INSERT INTO [dbo].[TB_M_WORKFLOW_D] (
		WORKFLOW_ID,
		WORKFLOW_SEQ, 	
		APPROVER,
		CREATED_DT,
		CREATED_BY,
		CHANGED_DT,
		CHANGED_BY
	) VALUES (
		@WORKFLOW_ID,
		@WORKFLOW_SEQ,
		@APPROVER,
		GETDATE(),
		@LOGIN_USER,
		GETDATE(),
		@LOGIN_USER
	)
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
	
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
