SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Auth_Function]
	@ROLE_ID VARCHAR(50)
AS
BEGIN  

	SELECT 
		F.FUNCTION_ID,
		F.FUNCTION_NAME,
		F.FUNCTION_DESC,
		F.MENU_ID,
		M.MENU_NAME,
		F.CREATED_DT,
		F.CREATED_BY,
		F.CHANGED_DT,
		F.CHANGED_BY
	FROM [dbo].[TB_M_FUNCTION] F
	JOIN [dbo].[TB_M_AUTH_FUNCTION] A ON A.[FUNCTION_ID] = F.[FUNCTION_ID]
	LEFT JOIN [dbo].[TB_M_MENU] M ON M.[MENU_ID] = F.[MENU_ID]
	WHERE A.ROLE_ID = @ROLE_ID
	
END
GO
