SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_AuthFunction_DeleteByRole]
	@ROLE_ID VARCHAR(50), 
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	
	BEGIN
	DELETE FROM [dbo].[TB_M_AUTH_FUNCTION]
	WHERE ROLE_ID = @ROLE_ID
	
	SET @RETURN_MSG = 'Successfully Delete Data'
	END
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
