CREATE OR ALTER PROCEDURE [dbo].[sp_Approval_Approve]
	@APPROVAL_ID		INT,
	@WORKFLOW_SEQ 	INT,
	@APPROVER 			VARCHAR(50),
	@REMARK					VARCHAR(255),
	@LOGIN_USER 		VARCHAR(255),
	@RETURN_MSG 		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	UPDATE [dbo].[TB_R_APPROVAL_D]
		SET [STATUS] = 1,
				[REMARK] = @REMARK,
				[CHANGED_BY] = @LOGIN_USER,
				[CHANGED_DT] = GETDATE()
	WHERE [APPROVAL_ID] = @APPROVAL_ID
		AND	[WORKFLOW_SEQ] = @WORKFLOW_SEQ
		AND	[APPROVER] = @APPROVER

	-- Check If Last Seq
	DECLARE @MAX_SEQ INT
	SELECT @MAX_SEQ = MAX(WORKFLOW_SEQ) FROM [dbo].[TB_R_APPROVAL_D] WHERE [APPROVAL_ID] = @APPROVAL_ID

	IF (@WORKFLOW_SEQ = @MAX_SEQ)
	BEGIN
		UPDATE [dbo].[TB_R_APPROVAL_H]
			SET [APPROVAL_STATUS] = 1,
					[CHANGED_BY] = @LOGIN_USER,
					[CHANGED_DT] = GETDATE()
		WHERE [APPROVAL_ID] = @APPROVAL_ID
	END
	ELSE BEGIN
		-- Lanjut ke seq berikutnya yang benar-benar ada
		-- (urutan bisa melompat kalau ada langkah yang dilewati,
		--  mis. section tanpa Section Head)
		DECLARE @NEXT_SEQ INT
		SELECT @NEXT_SEQ = MIN(WORKFLOW_SEQ)
		FROM [dbo].[TB_R_APPROVAL_D]
		WHERE [APPROVAL_ID] = @APPROVAL_ID AND [WORKFLOW_SEQ] > @WORKFLOW_SEQ

		UPDATE [dbo].[TB_R_APPROVAL_H]
			SET [CURRENT_SEQ] = @NEXT_SEQ,
					[CHANGED_BY] = @LOGIN_USER,
					[CHANGED_DT] = GETDATE()
		WHERE [APPROVAL_ID] = @APPROVAL_ID
	END

	SET @RETURN_MSG = 'Successfully Approve Data'
	RETURN 1;

END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
