CREATE OR ALTER PROCEDURE [dbo].[sp_Approval_GetPendingByApprover]
    @APPROVER VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        A.APPROVAL_DETAIL_ID,
        A.APPROVAL_ID,
        A.WORKFLOW_SEQ,
        A.APPROVER,
        U.FULL_NAME AS APPROVER_NAME,
        A.STATUS,
        S.SYSTEM_VALUE AS STATUS_DESC,
        A.REMARK,
        A.LABEL,
        U.FILE_PATH,
        A.CREATED_DT,
        A.CREATED_BY,
        A.CHANGED_DT,
        A.CHANGED_BY,
        H.MENU_ID,
        H.TRANSACTION_ID,
        H.APPROVAL_DATE,
        H.CURRENT_SEQ,
        D.DOCUMENT_CODE,
        D.DOCUMENT_TRANSACTION_NAME
    FROM [dbo].[TB_R_APPROVAL_D] A
    JOIN [dbo].[TB_M_USER] U ON A.APPROVER = U.USERNAME
    LEFT JOIN [dbo].[TB_M_SYSTEM] S ON A.STATUS = S.SYSTEM_CODE AND S.SYSTEM_TYPE = 'APPROVAL_STATUS'
    LEFT JOIN [dbo].[TB_R_APPROVAL_H] H ON H.APPROVAL_ID = A.APPROVAL_ID
    LEFT JOIN [dbo].[TB_R_DOCUMENT] D ON D.DOCUMENT_TRANSACTION_ID = H.TRANSACTION_ID
    WHERE A.APPROVER = @APPROVER
      AND A.STATUS = '0'
    ORDER BY A.APPROVAL_ID, A.WORKFLOW_SEQ;
END
GO
