CREATE OR ALTER PROCEDURE [dbo].[sp_Approval_Delete]
	@APPROVAL_ID		 		int,
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	
	BEGIN
	DELETE FROM [dbo].[TB_R_APPROVAL_H]
	WHERE APPROVAL_ID = @APPROVAL_ID
				
  DELETE FROM [dbo].[TB_R_APPROVAL_D]
	WHERE APPROVAL_ID = @APPROVAL_ID
	
	SET @RETURN_MSG = 'Successfully Delete Data'
	END
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
