SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Auth_Menu]
	@ROLE_ID VARCHAR(50)
AS
BEGIN  

	SELECT 
		M.MENU_ID,
		M.MENU_NAME,
		M.MENU_ICON,
		M.MENU_URL,
		M.PARENT_ID,
		B.MENU_NAME AS PARENT_NAME,
		M.MENU_SEQ,
		M.CREATED_DT,
		M.CREATED_BY,
		M.CHANGED_DT,
		M.CHANGED_BY
	FROM [dbo].[TB_M_MENU] M
	JOIN [dbo].[TB_M_AUTH_MENU] A ON A.MENU_ID = M.MENU_ID
	LEFT JOIN [dbo].[TB_M_MENU] B ON M.[PARENT_ID] = B.[MENU_ID]
	WHERE A.ROLE_ID = @ROLE_ID
		AND ISNULL(M.DELETE_FLAG, 0) = 0
		AND ISNULL(B.DELETE_FLAG, 0) = 0
	ORDER BY M.MENU_SEQ ASC
END
GO
