SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Approval_Reject]
	@APPROVAL_ID		INT,
	@WORKFLOW_SEQ 	INT,
	@APPROVER 			VARCHAR(50),
	@REMARK					VARCHAR(255),
	@LOGIN_USER 		VARCHAR(255),
	@RETURN_MSG 		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	
	UPDATE [dbo].[TB_R_APPROVAL_D]
		SET [STATUS] = 2,
				[REMARK] = @REMARK,
				[CHANGED_BY] = @LOGIN_USER,
				[CHANGED_DT] = GETDATE()
	WHERE [APPROVAL_ID] = @APPROVAL_ID
		AND	[WORKFLOW_SEQ] = @WORKFLOW_SEQ
		AND	[APPROVER] = @APPROVER
		
	UPDATE [dbo].[TB_R_APPROVAL_H]
		SET [APPROVAL_STATUS] = 2,
				[CHANGED_BY] = @LOGIN_USER,
				[CHANGED_DT] = GETDATE()
	WHERE [APPROVAL_ID] = @APPROVAL_ID
	
	SET @RETURN_MSG = 'Successfully Reject Data'
	RETURN 1;	
	
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
