SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Auth_Login]
	@USERNAME VARCHAR(255)
AS
BEGIN

	SELECT
		A.USERNAME,
		A.REG_NO,
		A.FULL_NAME,
		A.PASSWORD,
		A.PASSWORD AS CONFIRM_PASSWORD,
		A.PASSWORD AS OLD_PASSWORD,
		A.EMAIL,
		A.PHONE,
		A.ROLE_ID,
		B.ROLE_NAME,
		P.POSITION_ID,
		P.POSITION_NAME,
		P.POSITION_LEVEL,
		C.DEPARTMENT_ID,
		D.DEPARTMENT_CODE,
		D.DEPARTMENT_NAME,
		C.DIVISION,
		(SELECT TOP 1 DOCUMENT_CONTROL_ACCESS FROM TB_M_DEPARTMENT MD LEFT JOIN TB_M_USER_POS MP ON MD.DIVISION = MP.DIVISION WHERE MP.USERNAME = A.USERNAME ORDER BY DOCUMENT_CONTROL_ACCESS DESC) AS DOCUMENT_CONTROL_ACCESS,
		E.DIVISION_NAME,
		F.SECTION_ID,
		F.SECTION_CODE,
		F.SECTION_NAME,
		A.FILE_PATH,
		A.SIGNATURE_PATH,
		A.AD_USER,
		A.CREATED_DT,
		A.CREATED_BY,
		A.CHANGED_DT,
		A.CHANGED_BY
	FROM [dbo].[TB_M_USER] A
  JOIN [dbo].[TB_M_ROLE] B ON B.ROLE_ID = A.ROLE_ID
	LEFT JOIN [dbo].[TB_M_USER_POS] C ON C.USERNAME = A.USERNAME
	LEFT JOIN [dbo].[TB_M_POSITION] P ON P.POSITION_ID = C.POSITION_ID
	LEFT JOIN [dbo].[TB_M_DEPARTMENT] D ON D.[DEPARTMENT_ID] = C.[DEPARTMENT_ID]
	LEFT JOIN [dbo].[TB_M_DIVISION] E ON E.[DIVISION_CODE] = C.[DIVISION]
	LEFT JOIN [dbo].[TB_M_SECTION] F ON F.[SECTION_ID] = C.[SECTION_ID]
	WHERE A.USERNAME = @USERNAME
	  AND ISNULL(A.DELETE_FLAG, '0') <> '1'

END
GO
