SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Approval_GetHistoryDetail]
	@APPROVAL_ID INT,
	@MENU_ID VARCHAR(50),
	@TRANSACTION_ID INT
AS
BEGIN

	DECLARE @QUERY VARCHAR(MAX)

	SET @QUERY = 'SELECT
									A.APPROVAL_DETAIL_ID,
									A.APPROVAL_ID,
									A.WORKFLOW_SEQ,
									A.APPROVER,
									U.FULL_NAME AS APPROVER_NAME,
									A.STATUS,
									S.SYSTEM_VALUE AS STATUS_DESC,
									A.REMARK,
									A.LABEL,
									U.FILE_PATH,
									A.CREATED_DT,
									A.CREATED_BY,
									A.CHANGED_DT,
									A.CHANGED_BY,
									H.MENU_ID,
									H.TRANSACTION_ID,
									H.APPROVAL_DATE,
									H.CURRENT_SEQ,
									D.DOCUMENT_CODE,
									D.DOCUMENT_TRANSACTION_NAME
								FROM [dbo].[TB_R_APPROVAL_D] A
								JOIN [dbo].[TB_M_USER] U ON A.APPROVER = U.USERNAME
								LEFT JOIN [dbo].[TB_M_SYSTEM] S ON A.STATUS = S.SYSTEM_CODE AND S.SYSTEM_TYPE = ''APPROVAL_STATUS''
								LEFT JOIN [dbo].[TB_R_APPROVAL_H] H ON H.APPROVAL_ID = A.APPROVAL_ID
								LEFT JOIN [dbo].[TB_R_DOCUMENT] D ON D.DOCUMENT_TRANSACTION_ID = H.TRANSACTION_ID
								WHERE 1 = 1 '

	IF @APPROVAL_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND A.APPROVAL_ID LIKE ''' + REPLACE(@APPROVAL_ID , '*', '%') + ''' '
	END

	IF @MENU_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND H.MENU_ID LIKE ''' + REPLACE(@MENU_ID , '*', '%') + ''' '
	END

	IF @TRANSACTION_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND H.TRANSACTION_ID LIKE ''' + REPLACE(@TRANSACTION_ID , '*', '%') + ''' '
	END

	SET @QUERY += ' ORDER BY A.CHANGED_DT ASC'

	EXEC(@QUERY)

END
GO
