SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_AuthFunction_Insert]
	@ROLE_ID VARCHAR(50), 
	@FUNCTION_ID VARCHAR(50),
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	INSERT INTO [dbo].[TB_M_AUTH_FUNCTION] (
		ROLE_ID, 
		FUNCTION_ID,
		CREATED_DT,
		CREATED_BY
	) VALUES (
		@ROLE_ID, 
		@FUNCTION_ID,
		GETDATE(),
		@LOGIN_USER
	)
	
	SET @RETURN_MSG = 'Successfully Save Data Function'
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
