SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Approval_GetHeader]
	@APPROVAL_ID	INT
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	
	SET @QUERY = 'SELECT 
									A.APPROVAL_ID,
									A.APPROVAL_DATE,
									A.APPROVAL_STATUS,
									A.CURRENT_SEQ,
									S.SYSTEM_VALUE AS APPROVAL_STATUS_DESC,
									A.CREATOR,
									U.FULL_NAME AS CREATOR_NAME,
									P.POSITION_NAME AS CREATOR_POSITION,
									A.CREATED_DT,
									A.CREATED_BY,
									A.CHANGED_DT,
									A.CHANGED_BY,
									A.MENU_ID,
									A.TRANSACTION_ID
								FROM [dbo].[TB_R_APPROVAL_H] A
								JOIN [dbo].[TB_M_USER] U ON A.CREATOR = U.USERNAME
								LEFT JOIN (SELECT USERNAME, MAX(POSITION_ID) POSITION_ID FROM [dbo].[TB_M_USER_POS] GROUP BY USERNAME) UP ON U.USERNAME = UP.USERNAME
								LEFT JOIN [dbo].[TB_M_POSITION] P ON UP.POSITION_ID = P.POSITION_ID
								LEFT JOIN [dbo].[TB_M_SYSTEM] S ON A.APPROVAL_STATUS = S.SYSTEM_CODE AND S.SYSTEM_TYPE = ''APPROVAL_STATUS''
								WHERE 1 = 1 '
								
	IF @APPROVAL_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND A.APPROVAL_ID LIKE ''' + REPLACE(@APPROVAL_ID , '*', '%') + ''' '
	END
	
	EXEC(@QUERY)
	
END
GO
