SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_CopyRequest_UpdateDetail]
	@REQUEST_DETAIL_ID       INT,
	@DOCUMENT_TRANSACTION_ID INT,
	@DOCUMENT_CODE           VARCHAR(100) = NULL,
	@DOCUMENT_NAME           VARCHAR(255) = NULL,
	@REVISION_NO             INT = NULL,
	@COPY_TYPE               VARCHAR(2) = NULL,
	@COPY_QTY                INT = NULL,
	@REASON                  VARCHAR(MAX) = NULL,
	@COUNTERMEASURE          VARCHAR(MAX) = NULL,
	@REMARKS                 VARCHAR(MAX) = NULL,
	@LOGIN_USER              VARCHAR(255),
	@RETURN_MSG              VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @RequestId INT, @CurrentStatus CHAR(1);
	SELECT @RequestId = D.REQUEST_ID, @CurrentStatus = H.STATUS
	FROM TB_R_COPY_REQUEST_D D
	JOIN TB_R_COPY_REQUEST_H H ON H.REQUEST_ID = D.REQUEST_ID
	WHERE D.REQUEST_DETAIL_ID = @REQUEST_DETAIL_ID AND D.DELETE_FLAG = 0;

	IF @RequestId IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document row not found';
		RETURN 0;
	END

	IF @CurrentStatus <> '0'
	BEGIN
		SET @RETURN_MSG = 'ERROR: Documents can only be edited while the request is still Draft';
		RETURN 0;
	END

	UPDATE [dbo].[TB_R_COPY_REQUEST_D]
	SET DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID,
		DOCUMENT_CODE = @DOCUMENT_CODE,
		DOCUMENT_NAME = @DOCUMENT_NAME,
		REVISION_NO = @REVISION_NO,
		COPY_TYPE = @COPY_TYPE,
		COPY_QTY = @COPY_QTY,
		REASON = @REASON,
		COUNTERMEASURE = @COUNTERMEASURE,
		REMARKS = @REMARKS,
		CHANGED_BY = @LOGIN_USER,
		CHANGED_DT = GETDATE()
	WHERE REQUEST_DETAIL_ID = @REQUEST_DETAIL_ID

	SET @RETURN_MSG = 'Successfully Save Data';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
