SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_CopyRequest_GetByKey]
	@REQUEST_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		H.REQUEST_ID,
		H.REQUEST_NO,
		H.DIVISION,
		ISNULL(H.DIVISION_NAME, DIV.DIVISION_NAME) AS DIVISION_NAME,
		H.DEPARTMENT_ID,
		ISNULL(H.DEPARTMENT_CODE, DEP.DEPARTMENT_CODE) AS DEPARTMENT_CODE,
		ISNULL(H.DEPARTMENT_NAME, DEP.DEPARTMENT_NAME) AS DEPARTMENT_NAME,
		H.SECTION_CODE,
		ISNULL(H.SECTION_NAME, SEC.SECTION_NAME) AS SECTION_NAME,
		H.REQUEST_DATE,
		H.DOC_CATEGORY,
		H.STATUS,
		SYS.SYSTEM_VALUE AS STATUS_DISPLAY,
		H.REQUESTED_BY,
		H.SUBMITTED_BY,
		H.SUBMITTED_DT,
		H.REMARK,
		H.APPROVED_BY,
		H.APPROVED_DT,
		H.APPROVAL_REMARK,
		(SELECT COUNT(*) FROM TB_R_COPY_REQUEST_D D WHERE D.REQUEST_ID = H.REQUEST_ID AND D.DELETE_FLAG = 0) AS DETAIL_COUNT,
		-- Parity dengan sp_CopyRequest_Search - keduanya FromSqlRaw ke model
		-- CopyRequest yang sama, jadi wajib SELECT kolom yang sama persis
		-- (request Hendra 2026-08-15).
		(SELECT COUNT(*) FROM TB_R_COPY_REQUEST_D D WHERE D.REQUEST_ID = H.REQUEST_ID AND D.DELETE_FLAG = 0 AND D.PRINT_STATUS = '1') AS PRINTED_COUNT,
		(SELECT ISNULL(SUM(L.TOTAL_SHEETS), 0) FROM TB_R_COPY_REQUEST_PRINT_LOG L
			INNER JOIN TB_R_COPY_REQUEST_D D2 ON D2.REQUEST_DETAIL_ID = L.REQUEST_DETAIL_ID
			WHERE D2.REQUEST_ID = H.REQUEST_ID AND L.PRINT_STATUS = 'Success') AS PRINTED_SHEETS,
		H.CREATED_BY,
		H.CREATED_DT,
		H.CHANGED_BY,
		H.CHANGED_DT
	FROM [dbo].[TB_R_COPY_REQUEST_H] H
	LEFT JOIN [dbo].[TB_M_SYSTEM] SYS ON SYS.SYSTEM_TYPE = 'COPY_REQUEST_STATUS' AND SYS.SYSTEM_CODE = H.STATUS
	LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = H.DIVISION
	LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = H.DEPARTMENT_ID
	LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = H.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
	WHERE H.REQUEST_ID = @REQUEST_ID AND H.DELETE_FLAG = 0;
END
GO
