SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_CopyRequest_GetByKey]
	@REQUEST_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		H.REQUEST_ID,
		H.REQUEST_NO,
		H.DIVISION,
		DIV.DIVISION_NAME,
		H.DEPARTMENT_ID,
		DEP.DEPARTMENT_CODE,
		DEP.DEPARTMENT_NAME,
		H.SECTION_CODE,
		SEC.SECTION_NAME,
		H.REQUEST_DATE,
		H.DOC_CATEGORY,
		H.STATUS,
		SYS.SYSTEM_VALUE AS STATUS_DISPLAY,
		H.REQUESTED_BY,
		H.SUBMITTED_BY,
		H.SUBMITTED_DT,
		H.REMARK,
		H.APPROVED_BY,
		H.APPROVED_DT,
		H.APPROVAL_REMARK,
		(SELECT COUNT(*) FROM TB_R_COPY_REQUEST_D D WHERE D.REQUEST_ID = H.REQUEST_ID AND D.DELETE_FLAG = 0) AS DETAIL_COUNT,
		H.CREATED_BY,
		H.CREATED_DT,
		H.CHANGED_BY,
		H.CHANGED_DT
	FROM [dbo].[TB_R_COPY_REQUEST_H] H
	LEFT JOIN [dbo].[TB_M_SYSTEM] SYS ON SYS.SYSTEM_TYPE = 'COPY_REQUEST_STATUS' AND SYS.SYSTEM_CODE = H.STATUS
	LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = H.DIVISION
	LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = H.DEPARTMENT_ID
	LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = H.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
	WHERE H.REQUEST_ID = @REQUEST_ID AND H.DELETE_FLAG = 0;
END
GO
