SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_CopyRequest_InsertDetail]
	@REQUEST_ID              INT,
	@DOCUMENT_TRANSACTION_ID INT,
	@DOCUMENT_CODE           VARCHAR(100) = NULL,
	@DOCUMENT_NAME           VARCHAR(255) = NULL,
	@REVISION_NO             INT = NULL,
	@COPY_TYPE               VARCHAR(2) = NULL,
	@COPY_QTY                INT = NULL,
	@REASON                  VARCHAR(MAX) = NULL,
	@COUNTERMEASURE          VARCHAR(MAX) = NULL,
	@REMARKS                 VARCHAR(MAX) = NULL,
	@LOGIN_USER              VARCHAR(255),
	@RETURN_MSG              VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @CurrentStatus CHAR(1);
	SELECT @CurrentStatus = STATUS FROM TB_R_COPY_REQUEST_H WHERE REQUEST_ID = @REQUEST_ID AND DELETE_FLAG = 0;

	IF @CurrentStatus IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Request not found';
		RETURN 0;
	END

	IF @CurrentStatus <> '0'
	BEGIN
		SET @RETURN_MSG = 'ERROR: Documents can only be added while the request is still Draft';
		RETURN 0;
	END

	DECLARE @NextLineNo INT;
	SELECT @NextLineNo = ISNULL(MAX(LINE_NO), 0) + 1 FROM TB_R_COPY_REQUEST_D WHERE REQUEST_ID = @REQUEST_ID AND DELETE_FLAG = 0;

	INSERT INTO [dbo].[TB_R_COPY_REQUEST_D] (
		REQUEST_ID, LINE_NO, DOCUMENT_TRANSACTION_ID, DOCUMENT_CODE, DOCUMENT_NAME, REVISION_NO,
		COPY_TYPE, COPY_QTY, REASON, COUNTERMEASURE, REMARKS,
		DELETE_FLAG, CREATED_BY, CREATED_DT, CHANGED_BY, CHANGED_DT
	) VALUES (
		@REQUEST_ID, @NextLineNo, @DOCUMENT_TRANSACTION_ID, @DOCUMENT_CODE, @DOCUMENT_NAME, @REVISION_NO,
		@COPY_TYPE, @COPY_QTY, @REASON, @COUNTERMEASURE, @REMARKS,
		0, @LOGIN_USER, GETDATE(), @LOGIN_USER, GETDATE()
	)

	SET @RETURN_MSG = 'Successfully Save Data';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
