SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_CopyRequest_DeleteDetail]
	@REQUEST_DETAIL_ID INT,
	@LOGIN_USER        VARCHAR(255),
	@RETURN_MSG        VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @RequestId INT, @CurrentStatus CHAR(1);
	SELECT @RequestId = D.REQUEST_ID, @CurrentStatus = H.STATUS
	FROM TB_R_COPY_REQUEST_D D
	JOIN TB_R_COPY_REQUEST_H H ON H.REQUEST_ID = D.REQUEST_ID
	WHERE D.REQUEST_DETAIL_ID = @REQUEST_DETAIL_ID AND D.DELETE_FLAG = 0;

	IF @RequestId IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document row not found';
		RETURN 0;
	END

	IF @CurrentStatus <> '0'
	BEGIN
		SET @RETURN_MSG = 'ERROR: Documents can only be removed while the request is still Draft';
		RETURN 0;
	END

	UPDATE [dbo].[TB_R_COPY_REQUEST_D]
	SET DELETE_FLAG = 1, CHANGED_BY = @LOGIN_USER, CHANGED_DT = GETDATE()
	WHERE REQUEST_DETAIL_ID = @REQUEST_DETAIL_ID;

	-- Resequence LINE_NO supaya nomor "No." di tabel & cetakan tetap rapi tanpa lubang
	;WITH renumbered AS (
		SELECT REQUEST_DETAIL_ID, ROW_NUMBER() OVER (ORDER BY LINE_NO ASC) AS NewLineNo
		FROM TB_R_COPY_REQUEST_D
		WHERE REQUEST_ID = @RequestId AND DELETE_FLAG = 0
	)
	UPDATE D
	SET D.LINE_NO = R.NewLineNo
	FROM TB_R_COPY_REQUEST_D D
	JOIN renumbered R ON R.REQUEST_DETAIL_ID = D.REQUEST_DETAIL_ID;

	SET @RETURN_MSG = 'Successfully Deleted';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
