SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_CopyRequest_SearchDetail]
	@REQUEST_ID INT,
	@PageNumber INT = NULL,
	@PageSize   INT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	;WITH data AS
	(
		SELECT
			ROW_NUMBER() OVER (ORDER BY D.LINE_NO ASC) as RowNumber,
			D.REQUEST_DETAIL_ID,
			D.REQUEST_ID,
			D.LINE_NO,
			D.DOCUMENT_TRANSACTION_ID,
			D.DOCUMENT_CODE,
			D.DOCUMENT_NAME,
			D.REVISION_NO,
			D.COPY_TYPE,
			COPYSYS.SYSTEM_VALUE AS COPY_TYPE_DISPLAY,
			D.COPY_QTY,
			D.REASON,
			D.COUNTERMEASURE,
			D.REMARKS,
			D.PRINT_STATUS,
			D.PRINTED_BY,
			D.PRINTED_DT,
			D.CREATED_BY,
			D.CREATED_DT,
			D.CHANGED_BY,
			D.CHANGED_DT
		FROM [dbo].[TB_R_COPY_REQUEST_D] D
		LEFT JOIN [dbo].[TB_M_SYSTEM] COPYSYS ON COPYSYS.SYSTEM_TYPE = 'DOC_SUBMISSION_COPY_TYPE' AND COPYSYS.SYSTEM_CODE = D.COPY_TYPE
		WHERE D.REQUEST_ID = @REQUEST_ID AND D.DELETE_FLAG = 0
	)
	SELECT * FROM data
	WHERE (@PageSize IS NULL OR @PageNumber IS NULL)
	OR (RowNumber > (@PageSize * (@PageNumber - 1)) AND RowNumber <= (@PageSize + (@PageSize * (@PageNumber - 1))))
	ORDER BY RowNumber;
END
GO
