SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Rewrite (2026-08-28, request Hendra): DocumentControlDashboard is the read-only
-- master document register. It used to be powered by sp_P4DMaintenance_Search, which
-- drives off TB_R_CTRL_DOCUMENT (the P4D distribution-registration table) - so a
-- document only showed up here AFTER someone manually "Add"-ed it into P4D
-- Maintenance. Legacy Document Import never creates a TB_R_CTRL_DOCUMENT row, so
-- imported master documents (already-effective in real life) were invisible on this
-- "master list" entirely - the bug Hendra flagged.
--
-- Now driven directly off TB_R_DOCUMENT (DOC) with TB_R_CTRL_DOCUMENT (S) as an
-- OPTIONAL left join (only for the P4D-specific columns: DOCUMENT_CTRL_ID,
-- registration STATUS/STATUS_VAL, LOCATION, REMARKS, OPERATION_TYPE) - a document
-- appears here as soon as it's Approved/Published regardless of P4D registration.
-- Grid key changes from DOCUMENT_CTRL_ID (nullable now) to DOCUMENT_TRANSACTION_ID
-- (always present, one row per TB_R_DOCUMENT revision) - see _GridView.cshtml.
--
-- @DOCUMENT_STATUS filters TB_R_DOCUMENT.STATUS (comma list, same pattern as the old
-- @STATUS param elsewhere). Defaults to '1,5' (Approved/Published) when not passed -
-- that is what "master document" means here: excludes Waiting Approval/Rejected/
-- Deleted/Obsolete/Waiting Acknowledgment rows, which belong to the in-flight
-- Document Maintenance grid or the History popup, not the master register.
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentControlDashboard_Search]
	@DOCUMENT_TRANSACTION_ID	INT				= NULL,
	@DOCUMENT_CODE				VARCHAR(255)	= NULL,
	@DOCUMENT_NAME				VARCHAR(255)	= NULL,
	@DIVISION					VARCHAR(50)		= NULL,
	@DEPARTMENT_ID				INT				= NULL,
	@YEAR						VARCHAR(4)		= NULL,
	@DOCUMENT_STATUS			VARCHAR(50)		= NULL,
	@PageNumber					INT				= NULL,
	@PageSize					INT				= NULL
AS
BEGIN

	DECLARE @QUERY VARCHAR(MAX)
	DECLARE @DOC_STATUS_FILTER VARCHAR(50) = ISNULL(@DOCUMENT_STATUS, '1,5')

	SET @DOC_STATUS_FILTER = REPLACE(@DOC_STATUS_FILTER, ' ', '')
	SET @DOC_STATUS_FILTER = '''' + REPLACE(@DOC_STATUS_FILTER, ',', ''',''') + ''''

	SET @QUERY = 'WITH data AS
								(
									SELECT
										ROW_NUMBER() OVER (ORDER BY DOC.CHANGED_DT DESC) as RowNumber,
										S.DOCUMENT_CTRL_ID,
										DOC.DOCUMENT_TRANSACTION_ID,
										DOC.DOCUMENT_CODE,
										DOC.DOCUMENT_TRANSACTION_NAME AS DOCUMENT_NAME,
										ISNULL(B.SYSTEM_VALUE, '''') DOCUMENT_TYPE,
										DOC.PROCESS_CODE PROCESS_CODE,
										DOC.COMPANY_CODE COMPANY_CODE,
										DOC.SECTION_CODE SECTION_CODE,
										ISNULL(DOC.ITEM_CHANGED, '''') ITEM_CHANGED,
										ISNULL(DOC.REASON, '''') REASON,
										ISNULL(DOC.EXTERNAL_FLAG, '''') EXTERNAL_FLAG,
										ISNULL(DOC.REFERENCE_NO, '''') REFERENCE_NO,
										ISNULL(DOC.SOURCE, '''') SOURCE,
										CAST(DOC.DOCUMENT_DATE as date) DOCUMENT_DATE,
										ISNULL(DOC.FILE_PATH, '''') FILE_PATH,
										S.STATUS,
										ISNULL(A.SYSTEM_VALUE, '''') STATUS_VAL,
										ISNULL(DOC.REVISION, 0) REVISION,
										DOC.APPROVAL_ID APPROVAL_ID,
										ISNULL(DOC.DELETE_FLAG, 0) DELETE_FLAG,
										DOC.DIVISION DIVISION,
										ISNULL(DOC.DIVISION_NAME, DSYS.DIVISION_NAME) AS DIVISION_NAME,
										DOC.DEPARTMENT AS DEPARTMENT_ID,
										ISNULL(DOC.DEPARTMENT_CODE, D.DEPARTMENT_CODE) AS DEPARTMENT_CODE,
										'''' DISTRIBUTION,
										ISNULL(DOC.DEPARTMENT_NAME, D.DEPARTMENT_NAME) AS DEPARTMENT_NAME,
										DOC.CLASSIFIED,
										CLSYS.SYSTEM_VALUE AS CLASSIFIED_VAL,
										CAST(YEAR(DOC.DOCUMENT_DATE) as varchar(4)) DOCUMENT_YEAR,
										DOC.NEXT_REVIEW_DATE,
										S.LOCATION LOCATION,
										'''' IS_APPROVED,
										S.REMARKS REMARKS,
										'''' ACTION,
										S.OPERATION_TYPE,
										ISNULL(OSYS.SYSTEM_VALUE, '''') AS OPERATION_TYPE_VAL,
										(SELECT TOP 1 1 FROM TB_R_DOCUMENT_LOG WHERE DOCUMENT_TRANSACTION_ID = DOC.DOCUMENT_TRANSACTION_ID AND LOG_TYPE = ''4'') as PUBLISH_FLAG,
										MDOC.DOCUMENT_CODE AS CATEGORY_CODE,
										MDOC.DOCUMENT_NAME AS CATEGORY_NAME,
										DOC.STATUS AS DOC_STATUS,
										ISNULL(DOCSTAT.SYSTEM_VALUE, '''') AS DOC_STATUS_VAL,
										ISNULL(OWNERUSER.FULL_NAME, DOC.DOCUMENT_CREATOR) AS OWNER_FULL_NAME,
										(SELECT COUNT(*) FROM TB_R_DOCUMENT_DISTRIBUTION DD WHERE DD.DOCUMENT_TRANSACTION_ID = DOC.DOCUMENT_TRANSACTION_ID AND DD.STATUS = 1) AS ACK_TOTAL,
										(SELECT COUNT(*) FROM TB_R_DOCUMENT_DISTRIBUTION DD WHERE DD.DOCUMENT_TRANSACTION_ID = DOC.DOCUMENT_TRANSACTION_ID AND DD.STATUS = 1
											AND EXISTS (
												SELECT 1 FROM TB_R_PUBLISH_HISTORY PH
												JOIN TB_R_CTRL_DOCUMENT CT ON CT.DOCUMENT_CTRL_ID = PH.DOCUMENT_CTRL_ID
												WHERE CT.DOCUMENT_TRANSACTION_ID = DD.DOCUMENT_TRANSACTION_ID
												AND PH.DEPARTMENT_ID = DD.DEPARTMENT_ID
											)
										) AS ACK_DONE,
										(SELECT COUNT(DISTINCT DEP.DIVISION) FROM TB_R_DOCUMENT_DISTRIBUTION DD
											JOIN TB_M_DEPARTMENT DEP ON DEP.DEPARTMENT_ID = DD.DEPARTMENT_ID
											WHERE DD.DOCUMENT_TRANSACTION_ID = DOC.DOCUMENT_TRANSACTION_ID AND DD.STATUS = 1
										) AS DIVISION_COUNT,
										(SELECT COUNT(*) FROM TB_R_DOCUMENT_DISTRIBUTION DD
											WHERE DD.DOCUMENT_TRANSACTION_ID = DOC.DOCUMENT_TRANSACTION_ID AND DD.STATUS = 0
										) AS PENDING_DISTRIBUTION_COUNT,
										DOC.CREATED_BY,
										DOC.CREATED_DT,
										DOC.CHANGED_BY,
										DOC.CHANGED_DT,
										DOC.FOLDER_ID,
										FOLD.FOLDER_NAME
									FROM [dbo].[TB_R_DOCUMENT] DOC
									LEFT JOIN [dbo].[TB_R_CTRL_DOCUMENT] S
										ON S.DOCUMENT_TRANSACTION_ID = DOC.DOCUMENT_TRANSACTION_ID
											AND S.OPERATION_TYPE = 1
											AND ISNULL(S.DELETE_FLAG, 0) = 0
									LEFT JOIN TB_M_SYSTEM A
										ON A.SYSTEM_TYPE = ''DOC_CTRL_STATUS''
											AND A.SYSTEM_CODE = S.STATUS
									LEFT JOIN TB_M_SYSTEM B
										ON B.SYSTEM_TYPE = ''DOCUMENT_TYPE''
											AND B.SYSTEM_CODE = DOC.DOCUMENT_TYPE
									LEFT JOIN TB_M_SYSTEM OSYS
										ON OSYS.SYSTEM_TYPE = ''OPERATION_TYPE''
											AND OSYS.SYSTEM_CODE = S.OPERATION_TYPE
									LEFT JOIN TB_M_DEPARTMENT D
										ON D.DEPARTMENT_ID = DOC.DEPARTMENT
									LEFT JOIN TB_M_DIVISION DSYS
										ON DSYS.DIVISION_CODE = DOC.DIVISION
									JOIN TB_M_SYSTEM CLSYS
										ON CLSYS.SYSTEM_TYPE = ''CLASSIFIED''
											AND CLSYS.SYSTEM_CODE = ISNULL(DOC.CLASSIFIED, ''0'')
									LEFT JOIN TB_M_DOCUMENT MDOC
										ON MDOC.DOCUMENT_ID = DOC.DOCUMENT_ID
									LEFT JOIN TB_M_SYSTEM DOCSTAT
										ON DOCSTAT.SYSTEM_TYPE = ''DOC_STATUS''
											AND DOCSTAT.SYSTEM_CODE = DOC.STATUS
									LEFT JOIN TB_M_USER OWNERUSER
										ON OWNERUSER.USERNAME = DOC.DOCUMENT_CREATOR
									LEFT JOIN TB_M_DOCUMENT_FOLDER FOLD
										ON FOLD.FOLDER_ID = DOC.FOLDER_ID
									WHERE ISNULL(DOC.DELETE_FLAG, 0) = 0
									AND DOC.STATUS IN (' + @DOC_STATUS_FILTER + ')'

	IF @DEPARTMENT_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND DOC.DEPARTMENT = ' + CAST(@DEPARTMENT_ID AS VARCHAR)
	END

	IF @DIVISION IS NOT NULL
	BEGIN
		SET @QUERY += ' AND DOC.DIVISION LIKE ''' + REPLACE(@DIVISION, '*', '%') + ''' '
	END

	IF @DOCUMENT_TRANSACTION_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND DOC.DOCUMENT_TRANSACTION_ID = ' + CAST(@DOCUMENT_TRANSACTION_ID AS VARCHAR)
	END

	IF @DOCUMENT_CODE IS NOT NULL
	BEGIN
		SET @QUERY += ' AND DOC.DOCUMENT_CODE LIKE ''' + REPLACE(@DOCUMENT_CODE, '*', '%') + ''' '
	END

	IF @DOCUMENT_NAME IS NOT NULL
	BEGIN
		SET @QUERY += ' AND DOC.DOCUMENT_TRANSACTION_NAME LIKE ''' + REPLACE(@DOCUMENT_NAME, '*', '%') + ''' '
	END

	IF @YEAR IS NOT NULL
	BEGIN
		SET @QUERY += ' AND YEAR(DOC.DOCUMENT_DATE) = ''' + REPLACE(@YEAR, '*', '') + ''' '
	END

	SET @QUERY += '
								)
								SELECT * FROM data
								WHERE 1 = 1 '

	IF (@PageSize IS NOT NULL AND @PageSize > 0) AND @PageNumber IS NOT NULL
	BEGIN
		SET @QUERY += ' AND RowNumber > ' + CAST((@PageSize * (@PageNumber - 1)) AS VARCHAR) + ' AND RowNumber <= ' + CAST(@PageSize + (@PageSize * (@PageNumber - 1)) AS VARCHAR)
	END

	EXEC(@QUERY)

END
GO
