SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_DeleteDetail]
	@SUBMISSION_DETAIL_ID INT,
	@LOGIN_USER           VARCHAR(255),
	@RETURN_MSG           VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @SubmissionId INT, @CurrentStatus CHAR(1);
	SELECT @SubmissionId = D.SUBMISSION_ID, @CurrentStatus = H.STATUS
	FROM TB_R_DOC_SUBMISSION_FORM_D D
	JOIN TB_R_DOC_SUBMISSION_FORM_H H ON H.SUBMISSION_ID = D.SUBMISSION_ID
	WHERE D.SUBMISSION_DETAIL_ID = @SUBMISSION_DETAIL_ID AND D.DELETE_FLAG = 0;

	IF @SubmissionId IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document row not found';
		RETURN 0;
	END

	IF @CurrentStatus <> '0'
	BEGIN
		SET @RETURN_MSG = 'ERROR: Documents can only be removed while the submission is still Draft';
		RETURN 0;
	END

	UPDATE [dbo].[TB_R_DOC_SUBMISSION_FORM_D]
	SET DELETE_FLAG = 1, CHANGED_BY = @LOGIN_USER, CHANGED_DT = GETDATE()
	WHERE SUBMISSION_DETAIL_ID = @SUBMISSION_DETAIL_ID;

	-- Resequence LINE_NO supaya nomor "No." di tabel & cetakan tetap rapi tanpa lubang
	;WITH renumbered AS (
		SELECT SUBMISSION_DETAIL_ID, ROW_NUMBER() OVER (ORDER BY LINE_NO ASC) AS NewLineNo
		FROM TB_R_DOC_SUBMISSION_FORM_D
		WHERE SUBMISSION_ID = @SubmissionId AND DELETE_FLAG = 0
	)
	UPDATE D
	SET D.LINE_NO = R.NewLineNo
	FROM TB_R_DOC_SUBMISSION_FORM_D D
	JOIN renumbered R ON R.SUBMISSION_DETAIL_ID = D.SUBMISSION_DETAIL_ID;

	SET @RETURN_MSG = 'Successfully Deleted';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
