CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaintenance_MarkReviewReminded]
	@DOCUMENT_TRANSACTION_ID	INT
AS
BEGIN

	UPDATE [dbo].[TB_R_DOCUMENT]
	SET LAST_REVIEW_REMINDER_DT = GETDATE()
	WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID

END
GO
