CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentControlDashboard_SendDocument]
		@DOCUMENT_TRANSACTION_ID int,
		@LOGIN_USER varchar(50),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT

AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT
	, @LOCATION VARCHAR(255) = 'sp_DocumentControlDashboard_SendDocument'
	, @rev_REVISION int
	, @cur_STATUS char(1)
	, @cur_DOCUMENT_NO varchar(5)
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'IAD Dashboard', 'Send Document', @LOCATION, @LOGIN_USER
	
	SELECT @cur_STATUS = [STATUS]
		, @cur_DOCUMENT_NO = DOCUMENT_CODE
	FROM TB_R_CTRL_DOCUMENT
	WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND DELETE_FLAG != '1'

	UPDATE TB_R_CTRL_DOCUMENT
	SET [STATUS] = '5' --IIF(@IS_APPROVED = 'Y', '2', '3')
		--, [REMARKS] = IIF(@IS_APPROVED = 'Y', [REMARKS], @REMARKS)
		, CHANGED_BY = @LOGIN_USER
		, CHANGED_DT = GETDATE()
	WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND DELETE_FLAG != '1'

	SET @RETURN_MSG = 'Successfully Send Document'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
