-- 2) sp_DocumentMaintenance_GetDueForReview - dipakai job reminder email,
--    tidak perlu nilai P4D asli, cukup NULL supaya kolom entity terpenuhi.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaintenance_GetDueForReview]
    @DAYS_AHEAD             INT,
    @REMINDER_THROTTLE_DAYS INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        S.DOCUMENT_TRANSACTION_ID,
        S.DOCUMENT_CODE,
        S.DOCUMENT_TRANSACTION_NAME,
        S.CLASSIFIED,
        CLSYS.SYSTEM_VALUE AS CLASSIFIED_VAL,
        ISNULL(S.STATUS, '0') AS STATUS,
        SYS.SYSTEM_VALUE AS STATUS_DISPLAY,
        ISNULL(S.REVISION, 0) AS REVISION,
        S.NEXT_REVIEW_DATE,
        ISNULL(S.ITEM_CHANGED, '') AS ITEM_CHANGED,
        ISNULL(S.REASON, '') AS REASON,
        ISNULL(S.REFERENCE_NO, '') AS REFERENCE_NO,
        ISNULL(S.SOURCE, '') AS SOURCE,
        S.CREATED_DT,
        S.CREATED_BY,
        S.CHANGED_DT,
        S.CHANGED_BY,
        '' AS DISTRIBUTION,
        S.APPROVAL_ID,
        S.DOCUMENT_TYPE,
        S.PROCESS_CODE,
        S.COMPANY_CODE,
        S.SECTION_CODE,
        SEC.SECTION_NAME,
        ISNULL(S.EXTERNAL_FLAG, '') AS EXTERNAL_FLAG,
        CAST(S.DOCUMENT_DATE AS DATE) AS DOCUMENT_DATE,
        ISNULL((SELECT MIN(HS.DOCUMENT_DATE) FROM TB_R_DOCUMENT_HISTORY HS WHERE HS.REVISION = 0 AND HS.DOCUMENT_CODE = S.DOCUMENT_CODE), S.DOCUMENT_DATE) AS DOCUMENT_REVISION_0_DATE,
        ISNULL(S.FILE_PATH, '') AS FILE_PATH,
        ISNULL(S.DELETE_FLAG, 0) AS DELETE_FLAG,
        ISNULL(S.DEPARTMENT, 0) AS DEPARTMENT_ID,
        D.DEPARTMENT_CODE AS DEPARTMENT_CODE,
        D.DEPARTMENT_NAME AS DEPARTMENT_NAME,
        CAST(YEAR(S.DOCUMENT_DATE) AS VARCHAR(4)) AS DOCUMENT_YEAR,
        S.DIVISION AS DIVISION,
        DSYS.DIVISION_NAME,
        '' AS IS_APPROVED,
        S.IMPACT_OTHER_FLAG,
        S.LEVEL_CODE,
        S.DOCUMENT_ID,
        S.DOCUMENT_CREATOR,
        DCAT.DOCUMENT_NAME,
        NULL AS P4D_STATUS_VAL
    FROM [dbo].[TB_R_DOCUMENT] S
    LEFT JOIN TB_M_DEPARTMENT D ON D.DEPARTMENT_ID = S.DEPARTMENT
    LEFT JOIN TB_M_SECTION SEC ON SEC.SECTION_CODE = S.SECTION_CODE AND SEC.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND GETDATE() BETWEEN SEC.VALID_FROM AND SEC.VALID_TO AND SEC.DELETE_FLAG != 1
    LEFT JOIN TB_M_SYSTEM SYS ON SYS.SYSTEM_TYPE = 'DOC_STATUS' AND SYS.SYSTEM_CODE = ISNULL(S.STATUS, '0')
    LEFT JOIN TB_M_SYSTEM CLSYS ON CLSYS.SYSTEM_TYPE = 'CLASSIFIED' AND CLSYS.SYSTEM_CODE = ISNULL(S.CLASSIFIED, '0')
    LEFT JOIN TB_M_DIVISION DSYS ON DSYS.DIVISION_CODE = ISNULL(S.DIVISION, '0')
    LEFT JOIN TB_M_DOCUMENT DCAT ON DCAT.DOCUMENT_ID = S.DOCUMENT_ID
    WHERE ISNULL(S.DELETE_FLAG, 0) = 0
    AND S.STATUS = '1'
    AND S.NEXT_REVIEW_DATE IS NOT NULL
    AND S.NEXT_REVIEW_DATE <= DATEADD(DAY, @DAYS_AHEAD, GETDATE())
    AND (S.LAST_REVIEW_REMINDER_DT IS NULL OR S.LAST_REVIEW_REMINDER_DT <= DATEADD(DAY, -@REMINDER_THROTTLE_DAYS, GETDATE()));

END
GO
