SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentFolder_Insert]
	@FOLDER_NAME	VARCHAR(255),
	@PARENT_ID		INT,
	@LOGIN_USER		VARCHAR(255),
	@RETURN_MSG		VARCHAR(MAX) OUTPUT,
	@RETURN_ID		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_DocumentFolder_Insert';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Document Control Dashboard', 'Folder Insert', @LOCATION, @LOGIN_USER

	IF @FOLDER_NAME IS NULL OR LEN(@FOLDER_NAME) < 1
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: Folder Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF @PARENT_ID IS NOT NULL AND NOT EXISTS (
		SELECT 1 FROM [dbo].[TB_M_DOCUMENT_FOLDER] WHERE FOLDER_ID = @PARENT_ID AND ISNULL(DELETE_FLAG, 0) = 0
	)
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: Parent folder not found';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF EXISTS (
		SELECT 1 FROM [dbo].[TB_M_DOCUMENT_FOLDER]
		WHERE FOLDER_NAME = @FOLDER_NAME
		AND ISNULL(PARENT_ID, 0) = ISNULL(@PARENT_ID, 0)
		AND ISNULL(DELETE_FLAG, 0) = 0
	)
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: A folder named ' + @FOLDER_NAME + ' already exists here';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	INSERT INTO [dbo].[TB_M_DOCUMENT_FOLDER] (
		FOLDER_NAME, PARENT_ID, DELETE_FLAG, CREATED_DT, CREATED_BY, CHANGED_DT, CHANGED_BY
	) VALUES (
		@FOLDER_NAME, @PARENT_ID, 0, GETDATE(), @LOGIN_USER, GETDATE(), @LOGIN_USER
	)

	SET @RETURN_ID = SCOPE_IDENTITY();
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_ID = 0;
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
