CREATE OR ALTER PROCEDURE [dbo].[sp_Dashboard_SearchDistributedDivisionCount]
	@USERNAME 				VARCHAR(255)
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	DECLARE @DIVISION_COUNT INT
	DECLARE @DIVISION_IAD_COUNT INT
	DECLARE @DEPARTMENT_COUNT INT
	
	SELECT @DIVISION_IAD_COUNT = COUNT(D.DOCUMENT_CONTROL_ACCESS) FROM TB_M_USER_POS P
	LEFT JOIN TB_M_DEPARTMENT D ON D.DIVISION = P.DIVISION
	WHERE P.USERNAME = @USERNAME
	AND D.DOCUMENT_CONTROL_ACCESS = 1;
	
	SET @QUERY = 'WITH data AS 
								(
									SELECT 
										S.DIVISION DIVISION,
										COUNT(DIVISION) AS DIVISION_COUNT
									FROM [dbo].[TB_R_CTRL_DOCUMENT] S
									WHERE 1 = 1
									AND ISNULL(S.DELETE_FLAG, 0) = 0 
									AND S.OPERATION_TYPE = 1
									AND S.STATUS IN (4,5) '
									
									IF @USERNAME IS NOT NULL AND @DIVISION_IAD_COUNT = 0
										BEGIN										
										SELECT @DIVISION_COUNT = COUNT(DIVISION) FROM TB_M_USER_POS WHERE USERNAME = @USERNAME;
										
										IF @DIVISION_COUNT > 0
										BEGIN
											SET @QUERY += ' AND S.DIVISION IN (SELECT DIVISION FROM TB_M_USER_POS WHERE USERNAME = '''+ @USERNAME+''') '
										END
									END
									
									IF @USERNAME IS NOT NULL AND @DIVISION_IAD_COUNT = 0
										BEGIN
										SELECT @DEPARTMENT_COUNT = COUNT(DEPARTMENT_ID) FROM TB_M_USER_POS WHERE USERNAME = @USERNAME;
										
										IF @DEPARTMENT_COUNT > 0
										BEGIN
											SET @QUERY += ' AND S.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM TB_M_USER_POS WHERE USERNAME = '''+ @USERNAME+''') '
										END
									END
									
	SET @QUERY += ' GROUP BY S.DIVISION
								)
								SELECT * FROM data
								WHERE 1 = 1 '
									
	EXEC(@QUERY)
	
END
GO
