SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentLog_Insert]
	@DOCUMENT_TRANSACTION_ID INT,
	@LOG_TYPE VARCHAR(50), 
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_DocumentLog_Insert';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Document Log', 'Insert', @LOCATION, @LOGIN_USER

	IF @DOCUMENT_TRANSACTION_ID IS NULL OR LEN(@DOCUMENT_TRANSACTION_ID) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document Transaction ID should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @LOG_TYPE IS NULL OR LEN(@LOG_TYPE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Log Type should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
-- 	LOG TYPE : 
-- 	1 = VIEW
-- 	2 = PRINT
-- 	3 = DOWNLOAD
-- 	4 = PUBLISH
	
	INSERT INTO [dbo].[TB_R_DOCUMENT_LOG] (
		DOCUMENT_TRANSACTION_ID,
		LOG_TYPE,
		CREATED_DT,
		CREATED_BY
	) VALUES (
		@DOCUMENT_TRANSACTION_ID,
		@LOG_TYPE, 
		GETDATE(),
		@LOGIN_USER
	)
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
