CREATE OR ALTER PROCEDURE [dbo].[sp_DepartmentMaster_GetByKey]
	@DEPARTMENT_ID INT,
	@DIVISION  		VARCHAR(50),
	@DOCUMENT_CONTROL_ACCESS VARCHAR(5)
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	
	SET @QUERY = 'SELECT 
										ROW_NUMBER() OVER (ORDER BY S.DEPARTMENT_CODE ASC) as RowNumber, 
										S.DEPARTMENT_ID,
										S.DEPARTMENT_CODE,
										S.DEPARTMENT_NAME,
										S.DEPARTMENT_CODE + '' - '' + S.DEPARTMENT_NAME AS DEPARTMENT_CODE_NAME,
										Y.DIVISION_CODE AS DIVISION,
										S.DOCUMENT_CONTROL_ACCESS,
										S.VALID_FROM,
										S.VALID_TO,
										S.CREATED_DT,
										S.CREATED_BY,
										S.CHANGED_DT,
										S.CHANGED_BY
									FROM [dbo].[TB_M_DEPARTMENT] S
									LEFT JOIN [dbo].[TB_M_DIVISION] Y ON Y.[DIVISION_CODE] = S.[DIVISION]
							WHERE 1 = 1 '
							
	IF @DEPARTMENT_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND S.DEPARTMENT_ID LIKE ''' + REPLACE(@DEPARTMENT_ID , '*', '%') + ''' '
	END
	
	IF @DIVISION IS NOT NULL
	BEGIN
		SET @QUERY += ' AND S.DIVISION LIKE ''' + REPLACE(@DIVISION , '*', '%') + ''' '
	END
	
	IF @DOCUMENT_CONTROL_ACCESS IS NOT NULL
	BEGIN
		SET @QUERY += ' AND S.DOCUMENT_CONTROL_ACCESS LIKE ''' + REPLACE(@DOCUMENT_CONTROL_ACCESS , '*', '%') + ''' '
	END
	
	EXEC(@QUERY)
	
END
GO
