SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaster_GetByKey]
	@DOCUMENT_ID INT
AS
BEGIN

	DECLARE @QUERY VARCHAR(MAX)

	SET @QUERY = 'SELECT
								D.DOCUMENT_ID,
								D.DOCUMENT_CODE,
								D.DOCUMENT_NAME,
								D.LEVEL,
								S.SYSTEM_VALUE AS LEVEL_VAL,
								D.FILE_PATH,
								D.REVIEW_CYCLE_MONTHS,
								D.CREATED_DT,
								D.CREATED_BY,
								D.CHANGED_DT,
								D.CHANGED_BY
							FROM [dbo].[TB_M_DOCUMENT] D
							LEFT JOIN [dbo].[TB_M_SYSTEM] S ON S.SYSTEM_TYPE = ''LEVEL_CODE'' AND S.SYSTEM_CODE = D.LEVEL
							WHERE 1 = 1 '

	IF @DOCUMENT_ID IS NOT NULL
	BEGIN
		SET @QUERY += ' AND D.DOCUMENT_ID LIKE ''' + REPLACE(@DOCUMENT_ID , '*', '%') + ''' '
	END

	EXEC(@QUERY)

END
GO
