CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaster_RemoveAttachment]
	@DOCUMENT_ID 	int,
	@LOGIN_USER 	VARCHAR(255),
	@RETURN_MSG 	VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	UPDATE [dbo].[TB_M_DOCUMENT]
	SET FILE_PATH = null,
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE DOCUMENT_ID = @DOCUMENT_ID
	
	SET @RETURN_MSG = 'Successfully Remove Template Data'
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
