SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_SearchDetail]
	@SUBMISSION_ID INT,
	@PageNumber    INT = NULL,
	@PageSize      INT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	;WITH data AS
	(
		SELECT
			ROW_NUMBER() OVER (ORDER BY D.LINE_NO ASC) as RowNumber,
			D.SUBMISSION_DETAIL_ID,
			D.SUBMISSION_ID,
			D.LINE_NO,
			D.DOCUMENT_NO,
			D.DOCUMENT_NAME,
			D.CLASSIFICATION,
			CSYS.SYSTEM_VALUE AS CLASSIFICATION_DISPLAY,
			D.SUBMISSION_TYPE,
			TSYS.SYSTEM_VALUE AS SUBMISSION_TYPE_DISPLAY,
			D.REVISION_NO,
			D.ITEM_CHANGED,
			D.REASON,
			D.EFFECTIVE_DATE,
			D.COPY_TYPE,
			COPYSYS.SYSTEM_VALUE AS COPY_TYPE_DISPLAY,
			D.COPY_QTY,
			D.DISTRIBUTION_DEPT_IDS,
			(
				SELECT STRING_AGG(DEP.DEPARTMENT_NAME, ', ')
				FROM STRING_SPLIT(D.DISTRIBUTION_DEPT_IDS, ',') S
				JOIN TB_M_DEPARTMENT DEP ON DEP.DEPARTMENT_ID = TRY_CAST(S.value AS INT)
			) AS DISTRIBUTION_DEPT_NAMES,
			D.CREATED_BY,
			D.CREATED_DT,
			D.CHANGED_BY,
			D.CHANGED_DT
		FROM [dbo].[TB_R_DOC_SUBMISSION_FORM_D] D
		LEFT JOIN [dbo].[TB_M_SYSTEM] CSYS ON CSYS.SYSTEM_TYPE = 'CLASSIFIED' AND CSYS.SYSTEM_CODE = CAST(D.CLASSIFICATION AS VARCHAR)
		LEFT JOIN [dbo].[TB_M_SYSTEM] TSYS ON TSYS.SYSTEM_TYPE = 'DOC_SUBMISSION_TYPE' AND TSYS.SYSTEM_CODE = D.SUBMISSION_TYPE
		LEFT JOIN [dbo].[TB_M_SYSTEM] COPYSYS ON COPYSYS.SYSTEM_TYPE = 'DOC_SUBMISSION_COPY_TYPE' AND COPYSYS.SYSTEM_CODE = D.COPY_TYPE
		WHERE D.SUBMISSION_ID = @SUBMISSION_ID AND D.DELETE_FLAG = 0
	)
	SELECT * FROM data
	WHERE (@PageSize IS NULL OR @PageNumber IS NULL)
	OR (RowNumber > (@PageSize * (@PageNumber - 1)) AND RowNumber <= (@PageSize + (@PageSize * (@PageNumber - 1))))
	ORDER BY RowNumber;
END
GO
