SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaintenance_Masterlist]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        D.DOCUMENT_TRANSACTION_ID,
        D.DOCUMENT_CODE,
        D.DOCUMENT_TRANSACTION_NAME,
        DCAT.DOCUMENT_NAME AS DOCUMENT_CATEGORY,
        D.DIVISION,
        ISNULL(D.DIVISION_NAME, DSYS.DIVISION_NAME) AS DIVISION_NAME,
        D.DEPARTMENT,
        ISNULL(D.DEPARTMENT_CODE, DEP.DEPARTMENT_CODE) AS DEPARTMENT_CODE,
        ISNULL(D.DEPARTMENT_NAME, DEP.DEPARTMENT_NAME) AS DEPARTMENT_NAME,
        CLSYS.SYSTEM_VALUE AS CLASSIFIED_VAL,
        D.REVISION,
        D.STATUS,
        SYS.SYSTEM_VALUE AS STATUS_DISPLAY,
        D.DOCUMENT_DATE,
        D.ITEM_CHANGED,
        D.REASON,
        D.DOCUMENT_CREATOR,
        D.FILE_PATH,
        D.CREATED_BY,
        D.CREATED_DT,
        D.CHANGED_BY,
        D.CHANGED_DT
    FROM [dbo].[TB_R_DOCUMENT] D
    LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = D.DEPARTMENT
    LEFT JOIN [dbo].[TB_M_DIVISION] DSYS ON DSYS.DIVISION_CODE = D.DIVISION
    LEFT JOIN [dbo].[TB_M_SYSTEM] SYS ON SYS.SYSTEM_TYPE = 'DOC_STATUS' AND SYS.SYSTEM_CODE = ISNULL(D.STATUS, '0')
    LEFT JOIN [dbo].[TB_M_SYSTEM] CLSYS ON CLSYS.SYSTEM_TYPE = 'CLASSIFIED' AND CLSYS.SYSTEM_CODE = ISNULL(D.CLASSIFIED, '0')
    LEFT JOIN [dbo].[TB_M_DOCUMENT] DCAT ON DCAT.DOCUMENT_ID = D.DOCUMENT_ID
    WHERE ISNULL(D.DELETE_FLAG, 0) = 0
    ORDER BY D.DOCUMENT_CODE;
END
GO
