SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaintenance_ImportLegacyInsert]
	@DOCUMENT_CODE				VARCHAR(25),
	@DOCUMENT_TRANSACTION_NAME	VARCHAR(255),
	@DOCUMENT_ID				INT,
	@LEVEL_CODE					INT,
	@DIVISION					VARCHAR(255),
	@DEPARTMENT					INT,
	@CLASSIFIED					INT,
	@REVISION					INT,
	@DOCUMENT_DATE				DATETIME,
	@FILE_PATH					VARCHAR(255),
	@DOCUMENT_CREATOR			VARCHAR(255),
	@REASON						VARCHAR(255),
	@CREATED_BY					VARCHAR(50),
	@RETURN_MSG					VARCHAR(MAX) OUTPUT,
	@RETURN_ID					VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT
	, @LOCATION VARCHAR(255) = 'sp_DocumentMaintenance_ImportLegacyInsert'
	, @REVIEW_CYCLE_MONTHS INT
	, @NEXT_REVIEW_DATE DATETIME

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Document Maintenance', 'Import Legacy Insert', @LOCATION, @CREATED_BY

	IF EXISTS (
		SELECT 1 FROM TB_R_DOCUMENT
		WHERE DOCUMENT_CODE = @DOCUMENT_CODE AND ISNULL(DELETE_FLAG, 0) = 0
	)
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: Document Code ' + @DOCUMENT_CODE + ' is already registered';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
		RETURN 0;
	END

	SELECT @REVIEW_CYCLE_MONTHS = REVIEW_CYCLE_MONTHS FROM TB_M_DOCUMENT WHERE DOCUMENT_ID = @DOCUMENT_ID

	IF @REVIEW_CYCLE_MONTHS IS NOT NULL
	BEGIN
		SET @NEXT_REVIEW_DATE = DATEADD(MONTH, @REVIEW_CYCLE_MONTHS, GETDATE())
	END

	-- Snapshot nama Division/Department (request Hendra 2026-08-22), lihat
	-- SQL/OrgMasterData_NameSnapshot_Migration.sql. Import Legacy tidak punya
	-- Section, jadi tidak ada snapshot Section di sini.
	DECLARE @snap_DIVISION_NAME VARCHAR(255), @snap_DEPARTMENT_CODE VARCHAR(5), @snap_DEPARTMENT_NAME VARCHAR(255);

	SELECT @snap_DIVISION_NAME = DIVISION_NAME FROM TB_M_DIVISION WHERE DIVISION_CODE = @DIVISION;
	SELECT @snap_DEPARTMENT_CODE = DEPARTMENT_CODE, @snap_DEPARTMENT_NAME = DEPARTMENT_NAME FROM TB_M_DEPARTMENT WHERE DEPARTMENT_ID = @DEPARTMENT;

	INSERT INTO [dbo].[TB_R_DOCUMENT]
		(DOCUMENT_CODE, DOCUMENT_TRANSACTION_NAME, DOCUMENT_ID, LEVEL_CODE, DIVISION, DIVISION_NAME, DEPARTMENT, DEPARTMENT_CODE, DEPARTMENT_NAME,
		 CLASSIFIED, REVISION, DOCUMENT_DATE, FILE_PATH, DOCUMENT_CREATOR, REASON, SOURCE,
		 STATUS, APPROVAL_ID, DELETE_FLAG, NEXT_REVIEW_DATE,
		 CREATED_BY, CREATED_DT, CHANGED_BY, CHANGED_DT)
	VALUES
		(@DOCUMENT_CODE, @DOCUMENT_TRANSACTION_NAME, @DOCUMENT_ID, @LEVEL_CODE, @DIVISION, @snap_DIVISION_NAME, @DEPARTMENT, @snap_DEPARTMENT_CODE, @snap_DEPARTMENT_NAME,
		 @CLASSIFIED, @REVISION, @DOCUMENT_DATE, @FILE_PATH, @DOCUMENT_CREATOR, @REASON, 'MIGRATION',
		 '1', NULL, 0, @NEXT_REVIEW_DATE,
		 @CREATED_BY, GETDATE(), @CREATED_BY, GETDATE())

	SET @RETURN_ID = SCOPE_IDENTITY();
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @CREATED_BY
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_ID = 0;
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
	RETURN 0;
END CATCH
GO
