CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaintenance_Delete]
	@DOCUMENT_TRANSACTION_ID	  INT,
	@LOGIN_USER 		VARCHAR(255),
	@RETURN_MSG 		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_DocumentMaintenance_Delete';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Document Maintenance', 'Delete', @LOCATION, @LOGIN_USER
	
	IF EXISTS(SELECT 1
				FROM TB_R_DOCUMENT
				WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID
					AND DELETE_FLAG = 1)
	BEGIN
		SET @RETURN_MSG = 'Concurrent process has occurred for deletion process';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF EXISTS(SELECT 1
				FROM TB_R_DOCUMENT
				WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID
					AND DELETE_FLAG = 0
					AND STATUS <> 0)
	BEGIN
		SET @RETURN_MSG = 'Delete data is not allowed for processed status';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	BEGIN
	UPDATE [dbo].[TB_R_DOCUMENT]
	SET DELETE_FLAG = 1,
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID	
	
	DELETE FROM TB_R_DOCUMENT_LOG WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID
	DELETE FROM TB_R_DOCUMENT_DISTRIBUTION WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID
	
	SET @RETURN_MSG = 'Successfully Delete Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	END
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
