SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_UpdateDetail]
	@SUBMISSION_DETAIL_ID    INT,
	@DOCUMENT_NO             VARCHAR(100) = NULL,
	@DOCUMENT_NAME           VARCHAR(255),
	@CLASSIFICATION          INT = NULL,
	@SUBMISSION_TYPE         VARCHAR(2),
	@REVISION_NO             INT = NULL,
	@ITEM_CHANGED            VARCHAR(MAX) = NULL,
	@REASON                  VARCHAR(MAX) = NULL,
	@EFFECTIVE_DATE          DATETIME = NULL,
	@COPY_TYPE               VARCHAR(2) = NULL,
	@COPY_QTY                INT = NULL,
	@DISTRIBUTION_DEPT_IDS   VARCHAR(500) = NULL,
	@LOGIN_USER              VARCHAR(255),
	@RETURN_MSG              VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @SubmissionId INT, @CurrentStatus CHAR(1);
	SELECT @SubmissionId = D.SUBMISSION_ID, @CurrentStatus = H.STATUS
	FROM TB_R_DOC_SUBMISSION_FORM_D D
	JOIN TB_R_DOC_SUBMISSION_FORM_H H ON H.SUBMISSION_ID = D.SUBMISSION_ID
	WHERE D.SUBMISSION_DETAIL_ID = @SUBMISSION_DETAIL_ID AND D.DELETE_FLAG = 0;

	IF @SubmissionId IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document row not found';
		RETURN 0;
	END

	IF @CurrentStatus <> '0'
	BEGIN
		SET @RETURN_MSG = 'ERROR: Documents can only be edited while the submission is still Draft';
		RETURN 0;
	END

	UPDATE [dbo].[TB_R_DOC_SUBMISSION_FORM_D]
	SET DOCUMENT_NO = @DOCUMENT_NO,
		DOCUMENT_NAME = @DOCUMENT_NAME,
		CLASSIFICATION = @CLASSIFICATION,
		SUBMISSION_TYPE = @SUBMISSION_TYPE,
		REVISION_NO = @REVISION_NO,
		ITEM_CHANGED = @ITEM_CHANGED,
		REASON = @REASON,
		EFFECTIVE_DATE = @EFFECTIVE_DATE,
		COPY_TYPE = @COPY_TYPE,
		COPY_QTY = @COPY_QTY,
		DISTRIBUTION_DEPT_IDS = @DISTRIBUTION_DEPT_IDS,
		CHANGED_BY = @LOGIN_USER,
		CHANGED_DT = GETDATE()
	WHERE SUBMISSION_DETAIL_ID = @SUBMISSION_DETAIL_ID

	SET @RETURN_MSG = 'Successfully Save Data';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
