SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_GetByKey]
	@SUBMISSION_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		H.SUBMISSION_ID,
		H.SUBMISSION_NO,
		H.DIVISION,
		DIV.DIVISION_NAME,
		H.DEPARTMENT_ID,
		DEP.DEPARTMENT_CODE,
		DEP.DEPARTMENT_NAME,
		H.SECTION_CODE,
		SEC.SECTION_NAME,
		H.SUBMISSION_DATE,
		H.DOC_CATEGORY,
		H.STATUS,
		SYS.SYSTEM_VALUE AS STATUS_DISPLAY,
		H.APPROVAL_ID,
		AH.APPROVAL_STATUS,
		AH.CURRENT_SEQ,
		H.DOCUMENT_CREATOR,
		H.SUBMITTED_BY,
		H.SUBMITTED_DT,
		H.REMARK,
		(SELECT COUNT(*) FROM TB_R_DOC_SUBMISSION_FORM_D D WHERE D.SUBMISSION_ID = H.SUBMISSION_ID AND D.DELETE_FLAG = 0) AS DETAIL_COUNT,
		H.CREATED_BY,
		H.CREATED_DT,
		H.CHANGED_BY,
		H.CHANGED_DT
	FROM [dbo].[TB_R_DOC_SUBMISSION_FORM_H] H
	LEFT JOIN [dbo].[TB_M_SYSTEM] SYS ON SYS.SYSTEM_TYPE = 'DOC_SUBMISSION_STATUS' AND SYS.SYSTEM_CODE = H.STATUS
	LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = H.DIVISION
	LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = H.DEPARTMENT_ID
	-- SECTION_CODE sendirian bukan unique - hanya unik per department, lihat
	-- catatan yang sama di sp_DocumentSubmission_Search.
	LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = H.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
	LEFT JOIN [dbo].[TB_R_APPROVAL_H] AH ON AH.APPROVAL_ID = H.APPROVAL_ID
	WHERE H.SUBMISSION_ID = @SUBMISSION_ID AND H.DELETE_FLAG = 0;
END
GO
