-- Returns one user's personal folder tree (all rows, unpaged) for the My
-- Documents sidebar - mirrors sp_DocumentFolder_Tree, scoped by @USERNAME.
-- DOCUMENT_COUNT comes from TB_R_DOCUMENT_FOLDER_PERSONAL (per-user assignment
-- table), not TB_R_DOCUMENT.FOLDER_ID (that's the global/Document Control one).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentFolderPersonal_Tree]
	@USERNAME	VARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		F.FOLDER_ID,
		F.PARENT_ID,
		B.FOLDER_NAME AS PARENT_NAME,
		F.FOLDER_NAME,
		F.USERNAME,
		ISNULL((
			SELECT COUNT(*) FROM [dbo].[TB_R_DOCUMENT_FOLDER_PERSONAL] UDF
			WHERE UDF.FOLDER_ID = F.FOLDER_ID
		), 0) AS DOCUMENT_COUNT,
		ISNULL(F.DELETE_FLAG, 0) AS DELETE_FLAG,
		F.CREATED_DT,
		F.CREATED_BY,
		F.CHANGED_DT,
		F.CHANGED_BY
	FROM [dbo].[TB_M_DOCUMENT_FOLDER_PERSONAL] F
	LEFT JOIN [dbo].[TB_M_DOCUMENT_FOLDER_PERSONAL] B ON F.PARENT_ID = B.FOLDER_ID
	WHERE ISNULL(F.DELETE_FLAG, 0) = 0
	AND F.USERNAME = @USERNAME
	ORDER BY F.PARENT_ID ASC, F.FOLDER_NAME ASC
END
GO
