SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_InsertDetail]
	@SUBMISSION_ID           INT,
	@DOCUMENT_NO             VARCHAR(100) = NULL,
	@DOCUMENT_NAME           VARCHAR(255),
	@CLASSIFICATION          INT = NULL,
	@SUBMISSION_TYPE         VARCHAR(2),
	@REVISION_NO             INT = NULL,
	@ITEM_CHANGED            VARCHAR(MAX) = NULL,
	@REASON                  VARCHAR(MAX) = NULL,
	@EFFECTIVE_DATE          DATETIME = NULL,
	@COPY_TYPE               VARCHAR(2) = NULL,
	@COPY_QTY                INT = NULL,
	@DISTRIBUTION_DEPT_IDS   VARCHAR(500) = NULL,
	@LOGIN_USER              VARCHAR(255),
	@RETURN_MSG              VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @CurrentStatus CHAR(1);
	SELECT @CurrentStatus = STATUS FROM TB_R_DOC_SUBMISSION_FORM_H WHERE SUBMISSION_ID = @SUBMISSION_ID AND DELETE_FLAG = 0;

	IF @CurrentStatus IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Submission not found';
		RETURN 0;
	END

	IF @CurrentStatus <> '0'
	BEGIN
		SET @RETURN_MSG = 'ERROR: Documents can only be added while the submission is still Draft';
		RETURN 0;
	END

	DECLARE @NextLineNo INT;
	SELECT @NextLineNo = ISNULL(MAX(LINE_NO), 0) + 1 FROM TB_R_DOC_SUBMISSION_FORM_D WHERE SUBMISSION_ID = @SUBMISSION_ID AND DELETE_FLAG = 0;

	INSERT INTO [dbo].[TB_R_DOC_SUBMISSION_FORM_D] (
		SUBMISSION_ID, LINE_NO, DOCUMENT_NO, DOCUMENT_NAME, CLASSIFICATION, SUBMISSION_TYPE, REVISION_NO,
		ITEM_CHANGED, REASON, EFFECTIVE_DATE, COPY_TYPE, COPY_QTY, DISTRIBUTION_DEPT_IDS,
		DELETE_FLAG, CREATED_BY, CREATED_DT, CHANGED_BY, CHANGED_DT
	) VALUES (
		@SUBMISSION_ID, @NextLineNo, @DOCUMENT_NO, @DOCUMENT_NAME, @CLASSIFICATION, @SUBMISSION_TYPE, @REVISION_NO,
		@ITEM_CHANGED, @REASON, @EFFECTIVE_DATE, @COPY_TYPE, @COPY_QTY, @DISTRIBUTION_DEPT_IDS,
		0, @LOGIN_USER, GETDATE(), @LOGIN_USER, GETDATE()
	)

	SET @RETURN_MSG = 'Successfully Save Data';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
