-- Mirrors sp_DocumentFolder_Insert, scoped to @USERNAME - the parent-folder
-- existence check and the duplicate-name check are both scoped to that
-- username's own folders, so no user can attach a folder under (or collide
-- names with) another user's tree.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentFolderPersonal_Insert]
	@FOLDER_NAME	VARCHAR(255),
	@PARENT_ID		INT,
	@USERNAME		VARCHAR(255),
	@RETURN_MSG		VARCHAR(MAX) OUTPUT,
	@RETURN_ID		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_DocumentFolderPersonal_Insert';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'My Documents', 'Personal Folder Insert', @LOCATION, @USERNAME

	IF @FOLDER_NAME IS NULL OR LEN(@FOLDER_NAME) < 1
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: Folder Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @USERNAME
		RETURN 0;
	END

	IF @PARENT_ID IS NOT NULL AND NOT EXISTS (
		SELECT 1 FROM [dbo].[TB_M_DOCUMENT_FOLDER_PERSONAL]
		WHERE FOLDER_ID = @PARENT_ID AND USERNAME = @USERNAME AND ISNULL(DELETE_FLAG, 0) = 0
	)
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: Parent folder not found';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @USERNAME
		RETURN 0;
	END

	IF EXISTS (
		SELECT 1 FROM [dbo].[TB_M_DOCUMENT_FOLDER_PERSONAL]
		WHERE FOLDER_NAME = @FOLDER_NAME
		AND USERNAME = @USERNAME
		AND ISNULL(PARENT_ID, 0) = ISNULL(@PARENT_ID, 0)
		AND ISNULL(DELETE_FLAG, 0) = 0
	)
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: A folder named ' + @FOLDER_NAME + ' already exists here';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @USERNAME
		RETURN 0;
	END

	INSERT INTO [dbo].[TB_M_DOCUMENT_FOLDER_PERSONAL] (
		FOLDER_NAME, PARENT_ID, USERNAME, DELETE_FLAG, CREATED_DT, CREATED_BY, CHANGED_DT, CHANGED_BY
	) VALUES (
		@FOLDER_NAME, @PARENT_ID, @USERNAME, 0, GETDATE(), @USERNAME, GETDATE(), @USERNAME
	)

	SET @RETURN_ID = SCOPE_IDENTITY();
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @USERNAME
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_ID = 0;
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @USERNAME
	RETURN 0;
END CATCH
GO
