CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaintenance_UpdateStatus]
	@DOCUMENT_TRANSACTION_ID				INT,
	@STATUS							VARCHAR(10),
	@LOGIN_USER 				VARCHAR(255),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	-- Periodic review (Jul 2026): on final approval, stamp NEXT_REVIEW_DATE using the
	-- document's category review cycle (TB_M_DOCUMENT.REVIEW_CYCLE_MONTHS). NULL cycle
	-- = category doesn't require periodic review. Reminder throttle is reset too, since
	-- this is effectively a fresh review clock.
	DECLARE @REVIEW_CYCLE_MONTHS INT
	DECLARE @NEXT_REVIEW_DATE DATETIME

	IF @STATUS = '1'
	BEGIN
		SELECT @REVIEW_CYCLE_MONTHS = M.REVIEW_CYCLE_MONTHS
		FROM [dbo].[TB_R_DOCUMENT] S
		JOIN [dbo].[TB_M_DOCUMENT] M ON M.DOCUMENT_ID = S.DOCUMENT_ID
		WHERE S.DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID

		IF @REVIEW_CYCLE_MONTHS IS NOT NULL
		BEGIN
			SET @NEXT_REVIEW_DATE = DATEADD(MONTH, @REVIEW_CYCLE_MONTHS, GETDATE())
		END
	END

	UPDATE [dbo].[TB_R_DOCUMENT]
	SET
			STATUS						= @STATUS,
			NEXT_REVIEW_DATE			= CASE WHEN @STATUS = '1' THEN @NEXT_REVIEW_DATE ELSE NEXT_REVIEW_DATE END,
			LAST_REVIEW_REMINDER_DT	= CASE WHEN @STATUS = '1' THEN NULL ELSE LAST_REVIEW_REMINDER_DT END,
			CHANGED_DT 				= GETDATE(),
			CHANGED_BY 				= @LOGIN_USER
	WHERE DOCUMENT_TRANSACTION_ID 		= @DOCUMENT_TRANSACTION_ID

	SET @RETURN_MSG = 'Successfully Update Status'
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
