SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DepartmentMaster_Update]
	@DEPARTMENT_ID			INT,
	@DEPARTMENT_CODE  	VARCHAR(5),
	@DEPARTMENT_NAME		VARCHAR(255),
	@DIVISION  					VARCHAR(50),
	@VALID_FROM				  DATE = NULL,
	@VALID_TO					  DATE = NULL,
	@LOGIN_USER 				VARCHAR(255),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_DepartmentMaster_Update';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Department Master', 'Update', @LOCATION, @LOGIN_USER

	-- Sama seperti sp_DepartmentMaster_Insert - param ini tidak pernah
	-- dikirim DepartmentMasterRepo.Update, dulu wajib diisi jadi Edit selalu
	-- gagal SQL error. Kalau tidak dikirim, pertahankan nilai yang sudah
	-- tersimpan (bukan default baru) supaya Edit nama/Division tidak diam-diam
	-- menimpa Valid From/To yang mungkin pernah di-set manual (bug ditemukan
	-- 2026-08-12).
	IF @VALID_FROM IS NULL OR @VALID_TO IS NULL
	BEGIN
		DECLARE @CUR_VALID_FROM DATE, @CUR_VALID_TO DATE;
		SELECT @CUR_VALID_FROM = VALID_FROM, @CUR_VALID_TO = VALID_TO
		FROM TB_M_DEPARTMENT WHERE DEPARTMENT_ID = @DEPARTMENT_ID;

		IF @VALID_FROM IS NULL SET @VALID_FROM = ISNULL(@CUR_VALID_FROM, CAST(GETDATE() AS DATE));
		IF @VALID_TO IS NULL SET @VALID_TO = ISNULL(@CUR_VALID_TO, '99991231');
	END

	IF @DEPARTMENT_CODE IS NULL OR LEN(@DEPARTMENT_CODE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Department Code should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @DEPARTMENT_NAME IS NULL OR LEN(@DEPARTMENT_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Department Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @DIVISION IS NULL OR LEN(@DIVISION) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Division should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @VALID_FROM IS NULL OR LEN(@VALID_FROM) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid From should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
			
	IF @VALID_TO IS NULL OR LEN(@VALID_TO) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid To should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @VALID_FROM > @VALID_TO
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid From cannot bigger than Valid To';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_DEPARTMENT] 
 	WHERE [DEPARTMENT_CODE] = @DEPARTMENT_CODE 
	AND [DEPARTMENT_ID] != @DEPARTMENT_ID
	AND DELETE_FLAG != 1)
	BEGIN
 			SET @RETURN_MSG = 'ERROR: Data already exist Department Code = ' + @DEPARTMENT_CODE;
			EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
			RETURN 0;
 	END
	
-- 	IF @WORKFLOW_ID IS NULL OR LEN(@WORKFLOW_ID) < 1
-- 	BEGIN
-- 		SET @RETURN_MSG = 'ERROR: Workflow should not be null';
-- 		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
-- 		RETURN 0;
-- 	END
	
	UPDATE [dbo].[TB_M_DEPARTMENT]
	SET DEPARTMENT_CODE	= @DEPARTMENT_CODE,
			DEPARTMENT_NAME = @DEPARTMENT_NAME,
			DIVISION = @DIVISION,
			VALID_FROM = @VALID_FROM,
			VALID_TO = @VALID_TO,
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE DEPARTMENT_ID = @DEPARTMENT_ID
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
