SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_Update]
	@SUBMISSION_ID     INT,
	@SECTION_CODE      VARCHAR(5) = NULL,
	@SUBMISSION_DATE   DATETIME,
	@DOC_CATEGORY      VARCHAR(200) = NULL,
	@REMARK            VARCHAR(MAX) = NULL,
	@LOGIN_USER        VARCHAR(255),
	@RETURN_MSG        VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @CurrentStatus CHAR(1);
	SELECT @CurrentStatus = STATUS FROM TB_R_DOC_SUBMISSION_FORM_H WHERE SUBMISSION_ID = @SUBMISSION_ID AND DELETE_FLAG = 0;

	IF @CurrentStatus IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Submission not found';
		RETURN 0;
	END

	IF @CurrentStatus <> '0'
	BEGIN
		SET @RETURN_MSG = 'ERROR: Only Draft submission can be edited';
		RETURN 0;
	END

	UPDATE [dbo].[TB_R_DOC_SUBMISSION_FORM_H]
	SET SECTION_CODE = @SECTION_CODE,
		SUBMISSION_DATE = @SUBMISSION_DATE,
		DOC_CATEGORY = @DOC_CATEGORY,
		REMARK = @REMARK,
		CHANGED_BY = @LOGIN_USER,
		CHANGED_DT = GETDATE()
	WHERE SUBMISSION_ID = @SUBMISSION_ID

	SET @RETURN_MSG = 'Successfully Save Data';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
