SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_UpdateStatus]
	@SUBMISSION_ID INT,
	@STATUS        CHAR(1),
	@LOGIN_USER    VARCHAR(255),
	@RETURN_MSG    VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	IF NOT EXISTS (SELECT 1 FROM TB_R_DOC_SUBMISSION_FORM_H WHERE SUBMISSION_ID = @SUBMISSION_ID AND DELETE_FLAG = 0)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Submission not found';
		RETURN 0;
	END

	UPDATE [dbo].[TB_R_DOC_SUBMISSION_FORM_H]
	SET STATUS = @STATUS, CHANGED_BY = @LOGIN_USER, CHANGED_DT = GETDATE()
	WHERE SUBMISSION_ID = @SUBMISSION_ID;

	SET @RETURN_MSG = 'Successfully Updated';
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
