SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentMaster_Update]
	@DOCUMENT_ID				INT,
	@DOCUMENT_CODE 			VARCHAR(5),
	@DOCUMENT_NAME 			VARCHAR(255),
	@LEVEL 							INT,
	@FILE_PATH					VARCHAR(255),
	@REVIEW_CYCLE_MONTHS			INT = NULL,
	@LOGIN_USER 				VARCHAR(255),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_DocumentMaster_Update';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Document Master', 'Update', @LOCATION, @LOGIN_USER

	IF @DOCUMENT_CODE IS NULL OR LEN(@DOCUMENT_CODE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document Code should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF @DOCUMENT_NAME IS NULL OR LEN(@DOCUMENT_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF @LEVEL IS NULL OR LEN(@LEVEL) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Level should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF @FILE_PATH IS NULL OR LEN(@FILE_PATH) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Template should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	UPDATE [dbo].[TB_M_DOCUMENT]
	SET DOCUMENT_CODE = @DOCUMENT_CODE,
			DOCUMENT_NAME = @DOCUMENT_NAME,
			[LEVEL]= @LEVEL,
			FILE_PATH = @FILE_PATH,
			REVIEW_CYCLE_MONTHS = @REVIEW_CYCLE_MONTHS,
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE DOCUMENT_ID = @DOCUMENT_ID

	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
