SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DivisionMaster_Update]
	@DIVISION_ID				INT,
	@DIVISION_CODE  		VARCHAR(5),
	@DIVISION_NAME			VARCHAR(255),
	@VALID_FROM				  DATE = NULL,
	@VALID_TO					  DATE = NULL,
	@LOGIN_USER 				VARCHAR(255),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_DivisionMaster_Update';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Division Master', 'Update', @LOCATION, @LOGIN_USER

	-- Sama seperti sp_DivisionMaster_Insert - param ini tidak pernah dikirim
	-- DivisionMasterRepo.Update, dulu wajib diisi jadi Edit selalu gagal SQL
	-- error. Kalau tidak dikirim, pertahankan nilai yang sudah tersimpan
	-- (bukan default baru) supaya Edit nama/kode tidak diam-diam menimpa
	-- Valid From/To yang mungkin pernah di-set manual (bug ditemukan 2026-08-12).
	IF @VALID_FROM IS NULL OR @VALID_TO IS NULL
	BEGIN
		DECLARE @CUR_VALID_FROM DATE, @CUR_VALID_TO DATE;
		SELECT @CUR_VALID_FROM = VALID_FROM, @CUR_VALID_TO = VALID_TO
		FROM TB_M_DIVISION WHERE DIVISION_ID = @DIVISION_ID;

		IF @VALID_FROM IS NULL SET @VALID_FROM = ISNULL(@CUR_VALID_FROM, CAST(GETDATE() AS DATE));
		IF @VALID_TO IS NULL SET @VALID_TO = ISNULL(@CUR_VALID_TO, '99991231');
	END

	IF @DIVISION_CODE IS NULL OR LEN(@DIVISION_CODE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Division Code should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @DIVISION_NAME IS NULL OR LEN(@DIVISION_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Division Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @VALID_FROM IS NULL OR LEN(@VALID_FROM) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid From should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
			
	IF @VALID_TO IS NULL OR LEN(@VALID_TO) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid To should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @VALID_FROM > @VALID_TO
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid From cannot bigger than Valid To';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_DIVISION] 
 	WHERE [DIVISION_CODE] = @DIVISION_CODE
	AND [DIVISION_ID] != @DIVISION_ID
	AND DELETE_FLAG != 1)
	BEGIN
 			SET @RETURN_MSG = 'ERROR: Data already exist Division Code = ' + @DIVISION_CODE;
			EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
			RETURN 0;
 	END
	
	DECLARE @EXISTING_DIVISION_CODE VARCHAR(50);
	SET @EXISTING_DIVISION_CODE = (SELECT DIVISION_CODE FROM TB_M_DIVISION WHERE DIVISION_ID = @DIVISION_ID)
	
	IF @EXISTING_DIVISION_CODE != @DIVISION_CODE
	BEGIN
		UPDATE TB_M_USER_POS
		SET DIVISION = @DIVISION_CODE
		WHERE DIVISION = @EXISTING_DIVISION_CODE
		
		UPDATE TB_M_DEPARTMENT
		SET DIVISION = @DIVISION_CODE
		WHERE DIVISION = @EXISTING_DIVISION_CODE
		
		UPDATE TB_R_CTRL_DOCUMENT
		SET DIVISION = @DIVISION_CODE
		WHERE DIVISION = @EXISTING_DIVISION_CODE
		
		UPDATE TB_R_DOCUMENT
		SET DIVISION = @DIVISION_CODE
		WHERE DIVISION = @EXISTING_DIVISION_CODE
		
		UPDATE TB_R_DOCUMENT_HISTORY
		SET DIVISION = @DIVISION_CODE
		WHERE DIVISION = @EXISTING_DIVISION_CODE
	END
	
	UPDATE [dbo].[TB_M_DIVISION]
	SET DIVISION_CODE	= @DIVISION_CODE,
			DIVISION_NAME = @DIVISION_NAME,
			VALID_FROM = @VALID_FROM,
			VALID_TO = @VALID_TO,
			CHANGED_DT 		= GETDATE(),
			CHANGED_BY 		= @LOGIN_USER
	WHERE DIVISION_ID = @DIVISION_ID
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
