SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_DocumentSubmission_Search]
	@SUBMISSION_NO   VARCHAR(50) = NULL,
	@STATUS          CHAR(1) = NULL,
	@DIVISION        VARCHAR(50) = NULL,
	@DEPARTMENT_ID   INT = NULL,
	@PageNumber      INT = NULL,
	@PageSize        INT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	;WITH data AS
	(
		SELECT
			ROW_NUMBER() OVER (ORDER BY H.SUBMISSION_ID DESC) as RowNumber,
			H.SUBMISSION_ID,
			H.SUBMISSION_NO,
			H.DIVISION,
			ISNULL(H.DIVISION_NAME, DIV.DIVISION_NAME) AS DIVISION_NAME,
			H.DEPARTMENT_ID,
			ISNULL(H.DEPARTMENT_CODE, DEP.DEPARTMENT_CODE) AS DEPARTMENT_CODE,
			ISNULL(H.DEPARTMENT_NAME, DEP.DEPARTMENT_NAME) AS DEPARTMENT_NAME,
			H.SECTION_CODE,
			ISNULL(H.SECTION_NAME, SEC.SECTION_NAME) AS SECTION_NAME,
			H.SUBMISSION_DATE,
			H.DOC_CATEGORY,
			H.STATUS,
			SYS.SYSTEM_VALUE AS STATUS_DISPLAY,
			H.APPROVAL_ID,
			AH.APPROVAL_STATUS,
			AH.CURRENT_SEQ,
			H.DOCUMENT_CREATOR,
			H.SUBMITTED_BY,
			H.SUBMITTED_DT,
			H.REMARK,
			(SELECT COUNT(*) FROM TB_R_DOC_SUBMISSION_FORM_D D WHERE D.SUBMISSION_ID = H.SUBMISSION_ID AND D.DELETE_FLAG = 0) AS DETAIL_COUNT,
			H.CREATED_BY,
			H.CREATED_DT,
			H.CHANGED_BY,
			H.CHANGED_DT
		FROM [dbo].[TB_R_DOC_SUBMISSION_FORM_H] H
		LEFT JOIN [dbo].[TB_M_SYSTEM] SYS ON SYS.SYSTEM_TYPE = 'DOC_SUBMISSION_STATUS' AND SYS.SYSTEM_CODE = H.STATUS
		LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = H.DIVISION
		LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = H.DEPARTMENT_ID
		-- SECTION_CODE sendirian bukan unique - hanya unik per department (lihat
		-- TB_M_SECTION.DEPARTMENT_CODE) - tanpa syarat department di sini, join-nya
		-- fan-out ke SEMUA section dengan kode sama di department lain juga.
		LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = H.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
		LEFT JOIN [dbo].[TB_R_APPROVAL_H] AH ON AH.APPROVAL_ID = H.APPROVAL_ID
		WHERE H.DELETE_FLAG = 0
		AND (@SUBMISSION_NO IS NULL OR H.SUBMISSION_NO LIKE '%' + @SUBMISSION_NO + '%')
		AND (@STATUS IS NULL OR H.STATUS = @STATUS)
		AND (@DIVISION IS NULL OR H.DIVISION = @DIVISION)
		AND (@DEPARTMENT_ID IS NULL OR H.DEPARTMENT_ID = @DEPARTMENT_ID)
	)
	SELECT * FROM data
	WHERE (@PageSize IS NULL OR @PageNumber IS NULL)
	OR (RowNumber > (@PageSize * (@PageNumber - 1)) AND RowNumber <= (@PageSize + (@PageSize * (@PageNumber - 1))))
	ORDER BY RowNumber;
END
GO
