-- ============================================================
-- sp_ExternalDocument_Insert
-- ============================================================
CREATE OR ALTER PROCEDURE [dbo].[sp_ExternalDocument_Insert]
    @DOCUMENT_NAME       VARCHAR(255),
    @REVISION_EDITION    VARCHAR(50) = NULL,
    @RECEIVED_DATE       DATETIME = NULL,
    @EXTERNAL_TYPE       VARCHAR(255) = NULL,
    @STORAGE_LOCATION    VARCHAR(255) = NULL,
    @STORAGE_PIC         VARCHAR(255) = NULL,
    @REVIEW_FREQUENCY    VARCHAR(100) = NULL,
    @REVIEW_SOURCE       VARCHAR(255) = NULL,
    @LAST_CHECK_DATE     DATETIME = NULL,
    @REVIEW_CYCLE_MONTHS INT = NULL,
    @STATUS              INT = NULL,
    @INTERNAL_IMPACT     INT = NULL,
    @IMPACTED_DOCUMENT_TRANSACTION_ID INT = NULL,
    @DIVISION            VARCHAR(50) = NULL,
    @DEPARTMENT_ID       INT = NULL,
    @FILE_PATH           VARCHAR(255) = NULL,
    @LOGIN_USER          VARCHAR(255),
    @RETURN_MSG          VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
    DECLARE @PROCESS_ID BIGINT,
            @LOCATION VARCHAR(255) = 'sp_ExternalDocument_Insert',
            @NEXT_REVIEW_DATE DATETIME = NULL;

    EXEC sp_StartLog @PROCESS_ID OUTPUT, 'External Document', 'Insert', @LOCATION, @LOGIN_USER

    IF @DOCUMENT_NAME IS NULL OR LEN(@DOCUMENT_NAME) < 1
    BEGIN
        SET @RETURN_MSG = 'ERROR: Document Name should not be null';
        EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
        RETURN 0;
    END

    IF @LAST_CHECK_DATE IS NOT NULL AND @REVIEW_CYCLE_MONTHS IS NOT NULL
        SET @NEXT_REVIEW_DATE = DATEADD(MONTH, @REVIEW_CYCLE_MONTHS, @LAST_CHECK_DATE);

    INSERT INTO [dbo].[TB_M_EXTERNAL_DOCUMENT] (
        DOCUMENT_NAME, REVISION_EDITION, RECEIVED_DATE, EXTERNAL_TYPE,
        STORAGE_LOCATION, STORAGE_PIC, REVIEW_FREQUENCY, REVIEW_SOURCE,
        LAST_CHECK_DATE, REVIEW_CYCLE_MONTHS, NEXT_REVIEW_DATE,
        STATUS, INTERNAL_IMPACT, IMPACTED_DOCUMENT_TRANSACTION_ID,
        DIVISION, DEPARTMENT_ID, FILE_PATH,
        DELETE_FLAG, CREATED_DT, CREATED_BY, CHANGED_DT, CHANGED_BY
    ) VALUES (
        @DOCUMENT_NAME, @REVISION_EDITION, @RECEIVED_DATE, @EXTERNAL_TYPE,
        @STORAGE_LOCATION, @STORAGE_PIC, @REVIEW_FREQUENCY, @REVIEW_SOURCE,
        @LAST_CHECK_DATE, @REVIEW_CYCLE_MONTHS, @NEXT_REVIEW_DATE,
        @STATUS, @INTERNAL_IMPACT, @IMPACTED_DOCUMENT_TRANSACTION_ID,
        @DIVISION, @DEPARTMENT_ID, @FILE_PATH,
        0, GETDATE(), @LOGIN_USER, GETDATE(), @LOGIN_USER
    )

    SET @RETURN_MSG = 'Successfully Save Data'
    EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
    RETURN 1;
END TRY
BEGIN CATCH
    SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
    EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
    RETURN 0;
END CATCH
GO
