SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_ExternalDocument_GetDueForReview]
    @DAYS_AHEAD             INT,
    @REMINDER_THROTTLE_DAYS INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        E.EXTERNAL_DOCUMENT_ID,
        E.DOCUMENT_NAME,
        E.REVISION_EDITION,
        E.RECEIVED_DATE,
        E.EXTERNAL_TYPE,
        E.STORAGE_LOCATION,
        E.STORAGE_PIC,
        E.REVIEW_FREQUENCY,
        E.REVIEW_SOURCE,
        E.LAST_CHECK_DATE,
        E.REVIEW_CYCLE_MONTHS,
        E.NEXT_REVIEW_DATE,
        E.LAST_REVIEW_REMINDER_DT,
        E.STATUS,
        SSYS.SYSTEM_VALUE AS STATUS_DISPLAY,
        E.INTERNAL_IMPACT,
        ISYS.SYSTEM_VALUE AS INTERNAL_IMPACT_DISPLAY,
        E.IMPACTED_DOCUMENT_TRANSACTION_ID,
        RD.DOCUMENT_CODE AS IMPACTED_DOCUMENT_CODE,
        RD.DOCUMENT_TRANSACTION_NAME AS IMPACTED_DOCUMENT_NAME,
        E.DIVISION,
        DIV.DIVISION_NAME,
        E.DEPARTMENT_ID,
        DEP.DEPARTMENT_CODE,
        DEP.DEPARTMENT_NAME,
        E.FILE_PATH,
        E.CREATED_BY,
        E.CREATED_DT,
        E.CHANGED_BY,
        E.CHANGED_DT
    FROM [dbo].[TB_M_EXTERNAL_DOCUMENT] E
    LEFT JOIN [dbo].[TB_M_SYSTEM] SSYS ON SSYS.SYSTEM_TYPE = 'EXT_DOC_STATUS' AND SSYS.SYSTEM_CODE = CAST(E.STATUS AS VARCHAR)
    LEFT JOIN [dbo].[TB_M_SYSTEM] ISYS ON ISYS.SYSTEM_TYPE = 'EXT_DOC_IMPACT' AND ISYS.SYSTEM_CODE = CAST(E.INTERNAL_IMPACT AS VARCHAR)
    LEFT JOIN [dbo].[TB_R_DOCUMENT] RD ON RD.DOCUMENT_TRANSACTION_ID = E.IMPACTED_DOCUMENT_TRANSACTION_ID
    LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = E.DIVISION
    LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = E.DEPARTMENT_ID
    WHERE ISNULL(E.DELETE_FLAG, 0) = 0
    AND E.STATUS = 1
    AND E.NEXT_REVIEW_DATE IS NOT NULL
    AND E.NEXT_REVIEW_DATE <= DATEADD(DAY, @DAYS_AHEAD, GETDATE())
    AND (E.LAST_REVIEW_REMINDER_DT IS NULL OR E.LAST_REVIEW_REMINDER_DT <= DATEADD(DAY, -@REMINDER_THROTTLE_DAYS, GETDATE()));
END
GO
