CREATE OR ALTER PROCEDURE [dbo].[sp_Function_Update]
	@FUNCTION_ID VARCHAR(50), 
	@FUNCTION_NAME VARCHAR(255), 
	@FUNCTION_DESC VARCHAR(255), 
	@MENU_ID VARCHAR(50),
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Function_Update';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Menu & Function - Function', 'Update', @LOCATION, @LOGIN_USER	
	
	IF @FUNCTION_NAME IS NULL OR LEN(@FUNCTION_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Function Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	UPDATE [dbo].[TB_M_FUNCTION]
	SET FUNCTION_NAME = @FUNCTION_NAME, 
			FUNCTION_DESC = @FUNCTION_DESC, 
			MENU_ID = @MENU_ID,
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE FUNCTION_ID = @FUNCTION_ID
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
