CREATE OR ALTER PROCEDURE [dbo].[sp_Function_Insert]
	@FUNCTION_ID VARCHAR(50),
	@FUNCTION_NAME VARCHAR(255), 
	@FUNCTION_DESC VARCHAR(255), 
	@MENU_ID VARCHAR(50),
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Function_Insert';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Menu & Function - Function', 'Insert', @LOCATION, @LOGIN_USER

	IF @FUNCTION_ID IS NULL OR LEN(@FUNCTION_ID) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Function ID should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_FUNCTION] 
 	WHERE [FUNCTION_ID] = @FUNCTION_ID)
 	BEGIN
 			SET @RETURN_MSG = 'ERROR: Data already exist Function ID = ' + @FUNCTION_ID;
			EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
			RETURN 0;
 	END
	
	IF @FUNCTION_NAME IS NULL OR LEN(@FUNCTION_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Function Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @MENU_ID IS NULL OR LEN(@MENU_ID) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Menu should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	INSERT INTO [dbo].[TB_M_FUNCTION] (
		FUNCTION_ID,
		FUNCTION_NAME, 
		FUNCTION_DESC, 	
		MENU_ID,
		CREATED_DT,
		CREATED_BY
	) VALUES (
		@FUNCTION_ID,
		@FUNCTION_NAME, 
		@FUNCTION_DESC,
		@MENU_ID,
		GETDATE(),
		@LOGIN_USER
	)
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
