CREATE OR ALTER PROCEDURE [dbo].[sp_GetNextSeqNo]
	@SEQ_TYPE  	VARCHAR(50),
	@SEQ_CODE  	VARCHAR(50),
	@LOGIN_USER VARCHAR(255),
	@p_seq_no   INT OUTPUT 
AS
BEGIN  

	DECLARE @SEQ_NO INT;
	
	SELECT @SEQ_NO = SEQ_NO FROM TB_M_SEQUENCE 
	WHERE SEQ_TYPE = @SEQ_TYPE 
	AND SEQ_CODE = @SEQ_CODE
	
	IF @SEQ_NO IS NULL
	BEGIN
		INSERT INTO TB_M_SEQUENCE (
			SEQ_TYPE,
			SEQ_CODE,
			SEQ_NO,
			CREATED_BY,
			CREATED_DT,
			CHANGED_BY,
			CHANGED_DT
		) VALUES (
			@SEQ_TYPE,
			@SEQ_CODE,
			1,
			@LOGIN_USER,
			GETDATE(),
			@LOGIN_USER,
			GETDATE()
		);
		set @p_seq_no = 1;
	END
	ELSE BEGIN
		UPDATE TB_M_SEQUENCE
		SET SEQ_NO = (@SEQ_NO + 1),
				CHANGED_BY = @LOGIN_USER,
				CHANGED_DT = GETDATE()
		WHERE SEQ_TYPE = @SEQ_TYPE 
		AND SEQ_CODE = @SEQ_CODE;
		set @p_seq_no = @SEQ_NO + 1;
	END
	
END
GO
