CREATE OR ALTER PROCEDURE [dbo].[sp_GetMenuLastID]
	@PARENT_ID VARCHAR(50),
	@LAST_ID VARCHAR(MAX) OUTPUT
AS
BEGIN  

	DECLARE @SEQUENCE VARCHAR(3)
	
	IF @PARENT_ID IS NULL
	BEGIN
		SELECT @SEQUENCE = ISNULL(MAX(CAST(SUBSTRING(MENU_ID, 2, 5) AS INT)), 0) FROM [dbo].[TB_M_MENU] 
		WHERE PARENT_ID IS NULL
		
		SET @LAST_ID = 'M' + RIGHT('00000' + CAST((@SEQUENCE + 1) AS VARCHAR), 5)
	END
	ELSE BEGIN
		SELECT @SEQUENCE = ISNULL(MAX(CAST(SUBSTRING(MENU_ID, 8, 2) AS INT)), 0) FROM [dbo].[TB_M_MENU] 
		WHERE PARENT_ID = @PARENT_ID
		
		SET @LAST_ID = @PARENT_ID + '-' + RIGHT('00' + CAST((@SEQUENCE + 1) AS VARCHAR), 2)
	END
	
END
GO
