CREATE OR ALTER PROCEDURE [dbo].[sp_GetMenuLastSeq]
	@PARENT_ID VARCHAR(50),
	@LAST_SEQ VARCHAR(MAX) OUTPUT
AS
BEGIN  
	DECLARE @SEQUENCE INT
	
	IF @PARENT_ID IS NULL
	BEGIN
		SELECT @SEQUENCE = ISNULL(MAX(MENU_SEQ), 0) FROM [dbo].[TB_M_MENU] 
		WHERE PARENT_ID IS NULL
	END
	ELSE BEGIN
		SELECT @SEQUENCE = ISNULL(MAX(MENU_SEQ), 0) FROM [dbo].[TB_M_MENU] 
		WHERE PARENT_ID = @PARENT_ID
	END
	
	SET @LAST_SEQ = CAST((@SEQUENCE + 1) AS VARCHAR)
END
GO
