SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_MSystem_GetByKey]
	@SYSTEM_TYPE VARCHAR(50),
	@SYSTEM_CODE VARCHAR(50),
	@STATUS INT
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	
	SET @QUERY = 'SELECT 
								SYSTEM_TYPE,
								SYSTEM_CODE,
								SYSTEM_CODE + '' - '' + SYSTEM_VALUE AS SYSTEM_CODE_VALUE,
								SYSTEM_VALUE,
								STATUS,
								CREATED_DT,
								CREATED_BY,
								CHANGED_BY,
								CHANGED_DT
							FROM [dbo].[TB_M_SYSTEM] 
							WHERE 1 = 1 '
		
					
	IF @SYSTEM_TYPE IS NOT NULL
	BEGIN
		SET @QUERY += ' AND SYSTEM_TYPE LIKE ''' + REPLACE(@SYSTEM_TYPE , '*', '%') + ''' '
	END
	
	IF @SYSTEM_CODE IS NOT NULL
	BEGIN
		SET @QUERY += ' AND SYSTEM_CODE LIKE ''' + REPLACE(@SYSTEM_CODE , '*', '%') + ''' '
	END
	
	IF @STATUS IS NOT NULL
	BEGIN
		SET @QUERY += ' AND STATUS LIKE ''' + REPLACE(@STATUS , '*', '%') + ''' '
	END
	
	EXEC(@QUERY)
	
END
GO
