SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Menu_ToggleStatus]
	@MENU_ID VARCHAR(50),
	@DELETE_FLAG INT,
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Menu_ToggleStatus';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Menu & Function - Menu', 'ToggleStatus', @LOCATION, @LOGIN_USER

	UPDATE [dbo].[TB_M_MENU]
	SET DELETE_FLAG = @DELETE_FLAG,
		CHANGED_DT = GETDATE(),
		CHANGED_BY = @LOGIN_USER
	WHERE MENU_ID = @MENU_ID

	SET @RETURN_MSG = 'Successfully Update Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
