CREATE OR ALTER PROCEDURE [dbo].[sp_MSequence_GetByKey]
    @SEQ_TYPE VARCHAR(50),
    @SEQ_CODE VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT SEQ_TYPE, SEQ_CODE, SEQ_NO, CREATED_BY, CREATED_DT, CHANGED_BY, CHANGED_DT
    FROM [dbo].[TB_M_SEQUENCE]
    WHERE SEQ_TYPE = @SEQ_TYPE AND SEQ_CODE = @SEQ_CODE;
END
GO
