SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_MSystem_Insert]
	@SYSTEM_TYPE 	VARCHAR(50), 
	@SYSTEM_CODE 	VARCHAR(50), 
	@SYSTEM_VALUE VARCHAR(MAX),
	@STATUS 			INT,
	@LOGIN_USER 	VARCHAR(255),
	@RETURN_MSG 	VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_MSystem_Insert';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'System Master', 'Insert', @LOCATION, @LOGIN_USER
	
	IF @SYSTEM_TYPE IS NULL OR LEN(@SYSTEM_TYPE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: System Type should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @SYSTEM_CODE IS NULL OR LEN(@SYSTEM_CODE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: System Code should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @SYSTEM_VALUE IS NULL OR LEN(@SYSTEM_VALUE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: System Value should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_SYSTEM] 
 	WHERE  
 	[SYSTEM_TYPE] = @SYSTEM_TYPE
	AND
	[SYSTEM_CODE] = @SYSTEM_CODE)
 	BEGIN
 		SET @RETURN_MSG  = 'ERROR: Data with System Type = '+@SYSTEM_TYPE+' and Sytem Code = '+@SYSTEM_CODE+' already exist';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	INSERT INTO [dbo].[TB_M_SYSTEM] (
		SYSTEM_TYPE, 
		SYSTEM_CODE, 
		SYSTEM_VALUE,
		STATUS,
		CREATED_DT,
		CREATED_BY
	) VALUES (
		@SYSTEM_TYPE, 
		@SYSTEM_CODE, 
		@SYSTEM_VALUE,
		@STATUS,
		GETDATE(),
		@LOGIN_USER
	)
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
