SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Notification_Search]
	@USERNAME 	 VARCHAR(50)
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	
	SET @QUERY = 'SELECT
									NOTIFICATION_ID,
									NOTIFICATION_TEXT,
									NOTIFICATION_TITLE,
									NOTIFICATION_URL,
									NOTIFICATION_DATE,
									USERNAME,
									STATUS
								FROM TB_R_NOTIFICATION WHERE 1 = 1'
							
	IF @USERNAME IS NOT NULL
	BEGIN
		SET @QUERY += ' AND USERNAME = ''' + @USERNAME + ''' '
	END
	ELSE
	BEGIN
		SET @QUERY += ' AND 1 = 0 '
	END

	SET @QUERY += ' ORDER BY NOTIFICATION_DATE DESC '
	
	EXEC(@QUERY)
	
END
GO
