SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_NotificationSetting_Search]
AS
BEGIN TRY
	SET NOCOUNT ON;

	SELECT
		NOTIFICATION_TYPE,
		NOTIFICATION_LABEL,
		ISNULL(MODULE_NAME, '') MODULE_NAME,
		SEND_EMAIL,
		CREATED_BY,
		CREATED_DT,
		CHANGED_BY,
		CHANGED_DT
	FROM [dbo].[TB_M_NOTIFICATION_SETTING]
	ORDER BY MODULE_NAME, NOTIFICATION_LABEL;
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE() AS ERROR_MSG;
END CATCH
GO
