SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_NotificationSetting_ToggleEmail]
	@NOTIFICATION_TYPE VARCHAR(100),
	@SEND_EMAIL BIT,
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_NotificationSetting_ToggleEmail';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Notification Settings', 'ToggleEmail', @LOCATION, @LOGIN_USER

	UPDATE [dbo].[TB_M_NOTIFICATION_SETTING]
	SET SEND_EMAIL = @SEND_EMAIL,
		CHANGED_DT = GETDATE(),
		CHANGED_BY = @LOGIN_USER
	WHERE NOTIFICATION_TYPE = @NOTIFICATION_TYPE

	SET @RETURN_MSG = 'Successfully Update Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
