CREATE OR ALTER PROCEDURE [dbo].[sp_Notification_Insert]
	@NOTIFICATION_TEXT VARCHAR(MAX),
	@NOTIFICATION_TITLE VARCHAR(255),
	@NOTIFICATION_URL VARCHAR(255),
	@USERNAME VARCHAR(50),
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Notification_Insert';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Notification', 'Insert', @LOCATION, @LOGIN_USER

		
	INSERT INTO [dbo].[TB_R_NOTIFICATION] (
		NOTIFICATION_TEXT,
		NOTIFICATION_TITLE,
		NOTIFICATION_URL, 
		USERNAME, 	
		STATUS, 
		NOTIFICATION_DATE
	) VALUES (
		@NOTIFICATION_TEXT,
		@NOTIFICATION_TITLE,
		@NOTIFICATION_URL, 
		@USERNAME, 	
		0, 
		GETDATE()
	)
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
