CREATE OR ALTER PROCEDURE [dbo].[sp_PositionMaster_Update]
	@POSITION_ID				INT,
	@POSITION_NAME 			VARCHAR(255),
	@POSITION_LEVEL 		INT,
	@LOGIN_USER 				VARCHAR(255),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_PositionMaster_Update';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Position Master', 'Update', @LOCATION, @LOGIN_USER

	IF @POSITION_NAME IS NULL OR LEN(@POSITION_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Position Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF @POSITION_LEVEL IS NULL
	BEGIN
		SET @RETURN_MSG = 'ERROR: Position Level should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_POSITION]
	WHERE [POSITION_NAME] = @POSITION_NAME
	AND [POSITION_ID] != @POSITION_ID
	AND ISNULL([DELETE_FLAG], 0) != 1)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Data already exist Position Name = ' + @POSITION_NAME;
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	UPDATE [dbo].[TB_M_POSITION]
	SET POSITION_NAME 	= @POSITION_NAME,
			POSITION_LEVEL = @POSITION_LEVEL,
			CHANGED_DT 			= GETDATE(),
			CHANGED_BY 			= @LOGIN_USER
	WHERE POSITION_ID = @POSITION_ID

	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
