CREATE OR ALTER PROCEDURE [dbo].[sp_P4DMaintenance_Delete]
		@DOCUMENT_CTRL_ID int,
		@DOCUMENT_NO varchar(5),
		@LOGIN_USER varchar(50),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT

AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT
	, @LOCATION VARCHAR(255) = 'sp_P4DMaintenance_Delete'
	, @rev_DOCUMENT_ID int
	, @rev_REVISION int
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'P4D Maintenance', 'Delete', @LOCATION, @LOGIN_USER

	IF EXISTS(
		SELECT 1
		FROM TB_R_CTRL_DOCUMENT
		WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID
			AND [STATUS] NOT IN ('0', '1', '3')
	)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Only Document with status not received or rejected could be deleted';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	UPDATE TB_R_CTRL_DOCUMENT
	SET [STATUS] = '4'
		, CHANGED_BY = @LOGIN_USER
		, CHANGED_DT = GETDATE()
	WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID
	
	UPDATE TB_R_CTRL_DOCUMENT
	SET [DELETE_FLAG] = '1'
		, CHANGED_BY = @LOGIN_USER
		, CHANGED_DT = GETDATE()
	WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID
	
	DELETE FROM TB_R_DOCUMENT_LOG WHERE DOCUMENT_TRANSACTION_ID = (SELECT DOCUMENT_TRANSACTION_ID FROM TB_R_CTRL_DOCUMENT WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID)
	DELETE FROM TB_R_DOCUMENT_DISTRIBUTION WHERE DOCUMENT_TRANSACTION_ID = (SELECT DOCUMENT_TRANSACTION_ID FROM TB_R_CTRL_DOCUMENT WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID)

	SET @RETURN_MSG = 'Successfully Delete Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
