SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_P4DMaintenance_Search]
	@DOCUMENT_CTRL_ID 	INT,
	@DOCUMENT_TRANSACTION_ID 	INT,
	@DOCUMENT_CODE 	VARCHAR(255),
	@DOCUMENT_NAME 	VARCHAR(255),
	@DIVISION 	VARCHAR(50),
	@DEPARTMENT_ID  	INT,
	@DEPARTMENT_CODE  	VARCHAR(5),
	@YEAR		VARCHAR(4),
	@OPERATION_TYPE			INT,
	@STATUS							VARCHAR(50),
	@USERNAME						VARCHAR(255),
	@PageNumber 				int,
	@PageSize 					int,
	@DOCUMENT_STATUS		VARCHAR(10) = NULL		-- filter di TB_R_DOCUMENT.STATUS (dokumen master, mis. '5'=Published/fully acknowledged),
													-- beda dari @STATUS yang filter TB_R_CTRL_DOCUMENT.STATUS (status registrasi/distribusi P4D)
AS
BEGIN

	DECLARE @QUERY VARCHAR(MAX)
	DECLARE @DIVISION_COUNT INT
	DECLARE @DIVISION_IAD_COUNT INT
	DECLARE @DEPARTMENT_COUNT INT
	
		SELECT @DIVISION_IAD_COUNT = COUNT(D.DOCUMENT_CONTROL_ACCESS) FROM TB_M_USER_POS P
		LEFT JOIN TB_M_DEPARTMENT D ON D.DIVISION = P.DIVISION
		WHERE P.USERNAME = @USERNAME
		AND D.DOCUMENT_CONTROL_ACCESS = 1;
	
	SET @QUERY = 'WITH data AS 
								(
									SELECT 
										ROW_NUMBER() OVER (ORDER BY S.CHANGED_DT DESC) as RowNumber, 
										S.DOCUMENT_CTRL_ID,
										S.DOCUMENT_CODE,
										S.DOCUMENT_NAME,
										D.DEPARTMENT_NAME,
-- 										UD.DEPARTMENT_NAME AS CREATOR_DEPARTMENT_NAME,
										DOC.CLASSIFIED,
										CLSYS.SYSTEM_VALUE AS CLASSIFIED_VAL,
										S.STATUS,
										ISNULL(A.SYSTEM_VALUE, '''') STATUS_VAL,
										ISNULL(S.REVISION, 0) REVISION,
										ISNULL(S.ITEM_CHANGED, '''') ITEM_CHANGED,
										ISNULL(S.REASON, '''') REASON,
										ISNULL(S.REFERENCE_NO, '''') REFERENCE_NO,
										ISNULL(S.SOURCE, '''') SOURCE,
										S.CREATED_DT,
										S.CREATED_BY,
										S.CHANGED_DT,
										S.CHANGED_BY,
										'''' DISTRIBUTION,
										S.DOCUMENT_TRANSACTION_ID,
										S.APPROVAL_ID APPROVAL_ID,
										ISNULL(B.SYSTEM_VALUE, '''') DOCUMENT_TYPE,
										S.PROCESS_CODE PROCESS_CODE,
										S.COMPANY_CODE COMPANY_CODE,
										S.SECTION_CODE SECTION_CODE,
										ISNULL(S.EXTERNAL_FLAG, '''') EXTERNAL_FLAG,
										CAST(S.DOCUMENT_DATE as date) DOCUMENT_DATE,
										ISNULL(S.FILE_PATH, '''') FILE_PATH,
										ISNULL(S.DELETE_FLAG, 0) DELETE_FLAG,
										S.DEPARTMENT_ID,
-- 										P.DEPARTMENT_ID AS CREATOR_DEPARTMENT_ID,
										D.DEPARTMENT_CODE,
-- 										UD.DEPARTMENT_CODE AS CREATOR_DEPARTMENT_CODE,
										S.DOCUMENT_CODE DOCUMENT_NO,
										CAST(YEAR(S.DOCUMENT_DATE) as varchar(4)) DOCUMENT_YEAR,
										S.DIVISION DIVISION,
-- 										UD.DIVISION CREATOR_DIVISION,
										DSYS.DIVISION_NAME,
-- 										UDSYS.SYSTEM_VALUE AS CREATOR_DIVISION_NAME,
										S.LOCATION LOCATION,
										'''' IS_APPROVED,
										S.REMARKS REMARKS,
										S.OPERATION_TYPE,
										OSYS.SYSTEM_VALUE AS OPERATION_TYPE_VAL,
										'''' ACTION,
										(SELECT TOP 1 1 FROM TB_R_DOCUMENT_LOG WHERE DOCUMENT_TRANSACTION_ID = S.DOCUMENT_TRANSACTION_ID AND LOG_TYPE = ''4'') as PUBLISH_FLAG,
										DOC.NEXT_REVIEW_DATE,
										MDOC.DOCUMENT_CODE AS CATEGORY_CODE,
										MDOC.DOCUMENT_NAME AS CATEGORY_NAME,
										DOC.STATUS AS DOC_STATUS,
										ISNULL(DOCSTAT.SYSTEM_VALUE, '''') AS DOC_STATUS_VAL,
										ISNULL(OWNERUSER.FULL_NAME, DOC.DOCUMENT_CREATOR) AS OWNER_FULL_NAME,
										-- ACK_TOTAL/ACK_DONE dihitung dari TB_R_DOCUMENT_DISTRIBUTION (target
										-- department distribusi resmi), BUKAN dari jumlah baris TB_R_CTRL_DOCUMENT
										-- lagi - baris CTRL_DOCUMENT bisa nambah tiap ada user klik "Request
										-- Document" (OPERATION_TYPE=2), jadi kalau dipakai sebagai penyebut,
										-- rasio acknowledge jadi salah/menyesatkan (request user 2026-08-11).
										(SELECT COUNT(*) FROM TB_R_DOCUMENT_DISTRIBUTION DD WHERE DD.DOCUMENT_TRANSACTION_ID = S.DOCUMENT_TRANSACTION_ID AND DD.STATUS = 1) AS ACK_TOTAL,
										(SELECT COUNT(*) FROM TB_R_DOCUMENT_DISTRIBUTION DD WHERE DD.DOCUMENT_TRANSACTION_ID = S.DOCUMENT_TRANSACTION_ID AND DD.STATUS = 1
											AND EXISTS (
												SELECT 1 FROM TB_R_PUBLISH_HISTORY PH
												JOIN TB_R_CTRL_DOCUMENT CT ON CT.DOCUMENT_CTRL_ID = PH.DOCUMENT_CTRL_ID
												WHERE CT.DOCUMENT_TRANSACTION_ID = DD.DOCUMENT_TRANSACTION_ID
												AND PH.DEPARTMENT_ID = DD.DEPARTMENT_ID
											)
										) AS ACK_DONE
									FROM [dbo].[TB_R_CTRL_DOCUMENT] S
									JOIN TB_M_SYSTEM A
										ON A.SYSTEM_TYPE = ''DOC_CTRL_STATUS''
											AND A.SYSTEM_CODE = S.STATUS
									JOIN TB_M_SYSTEM B
										ON B.SYSTEM_TYPE = ''DOCUMENT_TYPE''
											AND B.SYSTEM_CODE = S.DOCUMENT_TYPE
									JOIN TB_M_DEPARTMENT D
										ON D.DEPARTMENT_ID = S.DEPARTMENT_ID
									JOIN TB_R_DOCUMENT DOC
										ON DOC.DOCUMENT_CODE = S.DOCUMENT_CODE
									LEFT JOIN TB_M_DOCUMENT MDOC
										ON MDOC.DOCUMENT_ID = DOC.DOCUMENT_ID
									LEFT JOIN TB_M_SYSTEM DOCSTAT
										ON DOCSTAT.SYSTEM_TYPE = ''DOC_STATUS''
											AND DOCSTAT.SYSTEM_CODE = DOC.STATUS
									LEFT JOIN TB_M_USER OWNERUSER
										ON OWNERUSER.USERNAME = DOC.DOCUMENT_CREATOR
									JOIN TB_M_SYSTEM CLSYS
										on CLSYS.SYSTEM_TYPE = ''CLASSIFIED''
											AND CLSYS.SYSTEM_CODE = ISNULL(DOC.CLASSIFIED, ''0'')
									JOIN TB_M_DIVISION DSYS
										on DSYS.DIVISION_CODE = ISNULL(S.DIVISION, ''0'')
									JOIN TB_M_SYSTEM OSYS
										on OSYS.SYSTEM_TYPE = ''OPERATION_TYPE''
											AND OSYS.SYSTEM_CODE = ISNULL(S.OPERATION_TYPE, ''0'')
									JOIN TB_M_USER US
										ON US.USERNAME = S.CREATED_BY
-- 									JOIN (SELECT USERNAME, MAX(POSITION_ID) POSITION_ID, MAX(DIVISION) DIVISION, MAX(DEPARTMENT_ID) DEPARTMENT_ID, MAX(SECTION_ID) SECTION_ID FROM [dbo].[TB_M_USER_POS] GROUP BY USERNAME) 
-- 									P ON US.[USERNAME] = P.[USERNAME]
-- 									JOIN TB_M_DEPARTMENT UD
-- 										ON UD.DEPARTMENT_ID = P.DEPARTMENT_ID
-- 									JOIN TB_M_SYSTEM UDSYS
-- 										on UDSYS.SYSTEM_TYPE = ''DIVISION''
-- 											AND UDSYS.SYSTEM_CODE = ISNULL(UD.DIVISION, ''0'')
									WHERE 1 = 1
									AND ISNULL(S.DELETE_FLAG, 0) = 0'	
									
									IF @DEPARTMENT_ID IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DEPARTMENT_ID LIKE ''' + REPLACE(@DEPARTMENT_ID , '*', '%') + ''' '
									END
									
									IF @DIVISION IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DIVISION LIKE ''' + REPLACE(@DIVISION , '*', '%') + ''' '
										--SET @QUERY += ' '
									END

									IF @DOCUMENT_CTRL_ID IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DOCUMENT_CTRL_ID LIKE ''' + REPLACE(@DOCUMENT_CTRL_ID , '*', '%') + ''' '
									END
									
									IF @DOCUMENT_CODE IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DOCUMENT_CODE LIKE ''' + REPLACE(@DOCUMENT_CODE , '*', '%') + ''' '
									END
									
									IF @DOCUMENT_NAME IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DOCUMENT_NAME LIKE ''' + REPLACE(@DOCUMENT_NAME , '*', '%') + ''' '
									END
									
									IF @YEAR IS NOT NULL
										BEGIN
										SET @QUERY += ' AND YEAR(S.DOCUMENT_DATE) = ''' + REPLACE(@YEAR , '*', '') + ''' '
									END
									
									IF @OPERATION_TYPE IS NOT NULL
										BEGIN
										SET @QUERY += ' AND S.OPERATION_TYPE = ''' + REPLACE(@OPERATION_TYPE , '*', '') + ''' '
									END
									
									IF @DOCUMENT_TRANSACTION_ID IS NOT NULL
										BEGIN
										SET @QUERY += ' AND S.DOCUMENT_TRANSACTION_ID = ''' + REPLACE(@DOCUMENT_TRANSACTION_ID , '*', '') + ''' '
									END
									
									IF @STATUS IS NOT NULL
										BEGIN
											SET @STATUS = REPLACE(@STATUS, ' ', '');  -- Remove any spaces
											SET @STATUS = '''' + REPLACE(@STATUS, ',', ''',''') + '''';  -- Convert commas to "','"
											
											SET @QUERY += ' AND S.STATUS IN (' + @STATUS + ')';
									END

									IF @DOCUMENT_STATUS IS NOT NULL
										BEGIN
										SET @QUERY += ' AND DOC.STATUS = ''' + @DOCUMENT_STATUS + ''' '
									END

									IF @USERNAME IS NOT NULL AND @DIVISION_IAD_COUNT = 0
										BEGIN										
										SELECT @DIVISION_COUNT = COUNT(DIVISION) FROM TB_M_USER_POS WHERE USERNAME = @USERNAME;
										
										IF @DIVISION_COUNT > 0
										BEGIN
											SET @QUERY += ' AND S.DIVISION IN (SELECT DIVISION FROM TB_M_USER_POS WHERE USERNAME = '''+ @USERNAME+''') '
										END
									END
									
									IF @USERNAME IS NOT NULL AND @DIVISION_IAD_COUNT = 0
										BEGIN
										SELECT @DEPARTMENT_COUNT = COUNT(DEPARTMENT_ID) FROM TB_M_USER_POS WHERE USERNAME = @USERNAME;
										
										IF @DEPARTMENT_COUNT > 0
										BEGIN
											SET @QUERY += ' AND S.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM TB_M_USER_POS WHERE USERNAME = '''+ @USERNAME+''') '
										END
									END

	SET @QUERY += ' 									
								)
								SELECT * FROM data
								WHERE 1 = 1 '
	
	IF (@PageSize IS NOT NULL AND @PageSize > 0) AND @PageNumber IS NOT NULL 
	BEGIN
		SET @QUERY += ' AND RowNumber > '+ CAST((@PageSize * (@PageNumber - 1)) AS VARCHAR) +' AND RowNumber <= ' +CAST(@PageSize + (@PageSize * (@PageNumber - 1)) AS VARCHAR);
	END
	EXEC(@QUERY)
	
END
GO
