CREATE OR ALTER PROCEDURE [dbo].[sp_PositionMaster_Delete]
	@POSITION_ID	INT,
	@LOGIN_USER 	VARCHAR(255),
	@RETURN_MSG 	VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_PositionMaster_Delete';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Position Master', 'Delete', @LOCATION, @LOGIN_USER

	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_USER_POS] WHERE POSITION_ID = @POSITION_ID)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Position is still assigned to one or more users, cannot be deleted';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	UPDATE [dbo].[TB_M_POSITION]
	SET DELETE_FLAG 	= 1,
			CHANGED_DT 		= GETDATE(),
			CHANGED_BY 		= @LOGIN_USER
	WHERE [POSITION_ID] = @POSITION_ID

	SET @RETURN_MSG = 'Successfully Delete Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
