SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_P4DMaintenance_Update]
		@DOCUMENT_CTRL_ID int,
		@DOCUMENT_CODE varchar(5),
		@LOCATION_DOC varchar(200),
		@CREATED_BY varchar(50),
		@CHANGED_BY varchar(50),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT

AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT
	, @LOCATION VARCHAR(255) = 'sp_P4DMaintenance_Update'
	, @rev_DOCUMENT_CTRL_ID int
	, @rev_REVISION int
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'P4D Maintenance', 'Insert', @LOCATION, @CREATED_BY

	IF NOT EXISTS(
		SELECT 1
		FROM TB_R_CTRL_DOCUMENT
		WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID
	)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document No ' + @DOCUMENT_CODE + ' is already delete by another user';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
		RETURN 0;
	END

	UPDATE TB_R_CTRL_DOCUMENT
	SET [LOCATION] = @LOCATION_DOC
		, CHANGED_BY = @CHANGED_BY
		, CHANGED_DT = GETDATE()
	WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID

	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @CREATED_BY
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
	RETURN 0;
END CATCH
GO
