CREATE OR ALTER PROCEDURE [dbo].[sp_P4DMaintenance_SendDistributionAll]
		@DOCUMENT_TRANSACTION_ID int,
		@LOGIN_USER varchar(50),
		@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT
	, @LOCATION VARCHAR(255) = 'sp_P4DMaintenance_SendDistributionAll'
	, @rev_DOCUMENT_ID int
	, @rev_REVISION int
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'P4D Maintenance', 'Send Distribution All', @LOCATION, @LOGIN_USER

	IF NOT EXISTS(
		SELECT 1
		FROM TB_R_DOCUMENT_DISTRIBUTION
		WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID
			--AND [STATUS] NOT IN ('0', '1', '3')
	)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Distribution Data is not found';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	update TB_R_DOCUMENT_DISTRIBUTION
	SET DISTRIBUTION_DATE = GETDATE()
		, STATUS = '1'
		, CHANGED_BY = @LOGIN_USER
		, CHANGED_DT = GETDATE()
	WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID
	AND STATUS = '0'
	
	UPDATE TB_R_CTRL_DOCUMENT
	SET [STATUS] = '5'
		, CHANGED_BY = @LOGIN_USER
		, CHANGED_DT = GETDATE()
	WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND DELETE_FLAG != '1'

	SET @RETURN_MSG = 'Successfully Send Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
