CREATE OR ALTER PROCEDURE [dbo].[sp_P4DMaintenance_ApproveReject]
		@DOCUMENT_CTRL_ID int,
		@DOCUMENT_CODE varchar(5),
		@IS_APPROVED varchar(1),
		@REMARKS varchar(200),
		@LOGIN_USER varchar(50),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT

AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT
	, @LOCATION VARCHAR(255) = 'sp_P4DMaintenance_ApproveReject'
	, @rev_DOCUMENT_CTRL_ID int
	, @rev_REVISION int
	, @cur_STATUS char(1)
	, @cur_DOCUMENT_NO varchar(5)
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'P4D Maintenance', 'ApproveReject', @LOCATION, @LOGIN_USER
	
	SELECT @cur_STATUS = [STATUS]
		, @cur_DOCUMENT_NO = DOCUMENT_CODE
	FROM TB_R_CTRL_DOCUMENT
	WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID

	IF @IS_APPROVED = 'Y' OR @IS_APPROVED = 'N'
	BEGIN
		IF @cur_STATUS = '4'
		BEGIN
			SET @RETURN_MSG = 'ERROR: Document No ' + IIF(ISNULL(@DOCUMENT_CODE, '') = '', @cur_DOCUMENT_NO, @DOCUMENT_CODE) + ' is already deleted';
			EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
			RETURN 0;
		END
	END

	IF @IS_APPROVED = 'N'
	BEGIN
		IF @cur_STATUS = '2'
		BEGIN
			SET @RETURN_MSG = 'ERROR: Document No ' + IIF(ISNULL(@DOCUMENT_CODE, '') = '', @cur_DOCUMENT_NO, @DOCUMENT_CODE) + ' is already received';
			EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
			RETURN 0;
		END
	END

	UPDATE TB_R_CTRL_DOCUMENT
	SET [STATUS] = IIF(@IS_APPROVED = 'Y', '2', '3')
		, [REMARKS] = IIF(@IS_APPROVED = 'Y', [REMARKS], @REMARKS)
		, CHANGED_BY = @LOGIN_USER
		, CHANGED_DT = GETDATE()
	WHERE DOCUMENT_CTRL_ID = @DOCUMENT_CTRL_ID

	SET @RETURN_MSG = 'Successfully '+ IIF(@IS_APPROVED = 'Y', 'Approve', 'Reject') +' Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
