CREATE OR ALTER PROCEDURE [dbo].[sp_Role_Insert]
	@ROLE_ID VARCHAR(50),
	@ROLE_NAME VARCHAR(255), 
	@ROLE_DESC VARCHAR(255), 
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Role_Insert';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Role Authorization - Role', 'Insert', @LOCATION, @LOGIN_USER	
	
	IF @ROLE_ID IS NULL OR LEN(@ROLE_ID) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Role ID should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @ROLE_NAME IS NULL OR LEN(@ROLE_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Role Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
--	DECLARE @ROLE_ID VARCHAR(50)
--	EXEC sp_GetLastID 'TB_M_ROLE', 'ROLE_ID', @ROLE_ID OUTPUT

	INSERT INTO [dbo].[TB_M_ROLE] (
		ROLE_ID,
		ROLE_NAME, 
		ROLE_DESC, 	
		CREATED_DT,
		CREATED_BY
	) VALUES (
		@ROLE_ID,
		@ROLE_NAME, 
		@ROLE_DESC, 
		GETDATE(),
		@LOGIN_USER
	)
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
