CREATE OR ALTER PROCEDURE [dbo].[sp_Role_Update]
	@ROLE_ID VARCHAR(50), 
	@ROLE_NAME VARCHAR(255), 
	@ROLE_DESC VARCHAR(255), 
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Role_Update';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Role Authorization - Role', 'Update', @LOCATION, @LOGIN_USER		
	
	IF @ROLE_NAME IS NULL OR LEN(@ROLE_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Role Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	UPDATE [dbo].[TB_M_ROLE]
	SET ROLE_NAME = @ROLE_NAME, 
			ROLE_DESC = @ROLE_DESC, 
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE ROLE_ID = @ROLE_ID
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
