CREATE OR ALTER PROCEDURE [dbo].[sp_SectionMaster_Insert]
	@SECTION_CODE 			VARCHAR(5),
	@SECTION_NAME 			VARCHAR(255),
	@DEPARTMENT_CODE    VARCHAR(5),
	@VALID_FROM 				DATE,
	@VALID_TO 					DATE,
	@LOGIN_USER 				VARCHAR(255),
	@RETURN_MSG 				VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_SectionMaster_Insert',
					@DATE_LIMIT AS DATE,
					@PREVIOUS_VALID_TO AS DATE;
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Section Master', 'Insert', @LOCATION, @LOGIN_USER

	IF @SECTION_CODE IS NULL OR LEN(@SECTION_CODE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Section Code should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @SECTION_NAME IS NULL OR LEN(@SECTION_NAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Section Name should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @DEPARTMENT_CODE IS NULL OR LEN(@DEPARTMENT_CODE) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Department Code should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @VALID_FROM IS NULL OR LEN(@VALID_FROM) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid From should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @VALID_TO IS NULL OR LEN(@VALID_TO) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid To should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
		
	IF @VALID_FROM > @VALID_TO
	BEGIN
		SET @RETURN_MSG = 'ERROR: Valid From cannot bigger than Valid To';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_SECTION] 
 	WHERE [SECTION_CODE] 	 = @SECTION_CODE
	AND   [DEPARTMENT_CODE]= @DEPARTMENT_CODE
	AND 	[DELETE_FLAG]		 != 1)
	
 	BEGIN
 			SET @RETURN_MSG = 'ERROR: Data already exist Section Code = ' + @SECTION_CODE + ' and Department = ' + @DEPARTMENT_CODE ;
			EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
			RETURN 0;
 	END
	
-- 	-- Check Last Valid To
-- 	SET @PREVIOUS_VALID_TO = (SELECT TOP 1 VALID_TO FROM [dbo].		[TB_M_SECTION]
-- 	WHERE DELETE_FLAG != 1
-- 	AND SECTION_CODE = @SECTION_CODE
-- 	AND DEPARTMENT_CODE = @DEPARTMENT_CODE
-- 	ORDER BY [CHANGED_DT] DESC)
-- 
-- 	IF @PREVIOUS_VALID_TO IS NOT NULL OR LEN(@PREVIOUS_VALID_TO) > 1
-- 	BEGIN	
-- 			SET @DATE_LIMIT = @PREVIOUS_VALID_TO
-- 
-- 			IF @PREVIOUS_VALID_TO = '9999-12-31'
-- 			BEGIN
-- 				SET @DATE_LIMIT = (SELECT TOP 1 VALID_FROM FROM [dbo].[TB_M_SECTION]
-- 				WHERE DELETE_FLAG != 1
-- 				AND SECTION_CODE = @SECTION_CODE
-- 				AND DEPARTMENT_CODE = @DEPARTMENT_CODE
-- 				ORDER BY [CHANGED_DT] DESC)
-- 			END
-- 			
-- 			IF @DATE_LIMIT > @VALID_TO
-- 			BEGIN	
-- 				SET @RETURN_MSG = 'ERROR: Valid From cannot smaller than last date, last date = ' + CAST(FORMAT (@DATE_LIMIT, 'dd-MM-yyyy') AS VARCHAR);
-- 				EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
-- 				RETURN 0;
-- 			END
-- 			ELSE BEGIN
-- 					-- Check Last Valid From				
-- 					IF @DATE_LIMIT IS NOT NULL OR LEN(@DATE_LIMIT) > 1
-- 					BEGIN	
-- 						IF @DATE_LIMIT >= @VALID_FROM
-- 						BEGIN	
-- 							SET @RETURN_MSG = 'ERROR: Valid From cannot smaller than last date, last date = ' + CAST(@DATE_LIMIT AS VARCHAR);
-- 							EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
-- 							RETURN 0;
-- 						END
-- 					ELSE BEGIN
-- 						UPDATE [dbo].[TB_M_SECTION]
-- 						SET VALID_TO = dateadd(DD, -1, cast(@VALID_FROM as date))
-- 						WHERE SECTION_CODE = @SECTION_CODE
-- 						AND DEPARTMENT_CODE = @DEPARTMENT_CODE
-- 						AND DELETE_FLAG != 1
-- 						AND CHANGED_DT = (select max(CHANGED_DT) from TB_M_SECTION WHERE DELETE_FLAG != 1 AND SECTION_CODE = @SECTION_CODE AND DEPARTMENT_CODE = @DEPARTMENT_CODE)
-- 						END
-- 					END
-- 					-- Check Last Valid From
-- 			END
-- 	END
-- 	-- Check Last Valid To	
	
	
	INSERT INTO [dbo].[TB_M_SECTION] (
		SECTION_CODE,
		SECTION_NAME,
		DEPARTMENT_CODE,
		VALID_FROM,
		VALID_TO,
		CREATED_DT,
		CREATED_BY,
		CHANGED_DT,
		CHANGED_BY
	) VALUES (
		@SECTION_CODE,
		@SECTION_NAME,
		@DEPARTMENT_CODE,
		@VALID_FROM,
		@VALID_TO,
		GETDATE(),
		@LOGIN_USER,
		GETDATE(),
		@LOGIN_USER
	)
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
