SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_SectionMaster_Delete]
	@SECTION_ID	    INT,
	@DELETE_FLAG    INT,
	@LOGIN_USER 		VARCHAR(255),
	@RETURN_MSG 		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_SectionMaster_Delete';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Section Master', 'Delete', @LOCATION, @LOGIN_USER		
	
	BEGIN
	UPDATE [dbo].[TB_M_SECTION]
	SET 	DELETE_FLAG 	 = 1,
				CHANGED_DT 		 = GETDATE(),
				CHANGED_BY 		 = @LOGIN_USER
	WHERE [SECTION_ID] 	 = @SECTION_ID
	
	SET @RETURN_MSG = 'Successfully Delete Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	END
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
