SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_UserDashboard_Search]
	@DOCUMENT_TRANSACTION_ID 	INT,
	@DOCUMENT_CODE 	VARCHAR(255),
	@DOCUMENT_NAME 	VARCHAR(255),
	@DIVISION 	VARCHAR(50),
	@DEPARTMENT_ID  	INT,
	@DEPARTMENT_CODE  	VARCHAR(5),
	@YEAR		VARCHAR(4),
	@LOGIN_USER 				VARCHAR(255),
	@PageNumber 				int,
	@PageSize 					int
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	DECLARE @DIVISION_COUNT INT
	DECLARE @DEPARTMENT_COUNT INT
	
	SET @QUERY = 'WITH data AS 
								(
									SELECT 
										ROW_NUMBER() OVER (ORDER BY S.DOCUMENT_CODE ASC) as RowNumber, 
										S.DOCUMENT_CTRL_ID,
										S.DOCUMENT_CODE,
										S.DOCUMENT_NAME,
										ISNULL(S.DEPARTMENT_NAME, D.DEPARTMENT_NAME) AS DEPARTMENT_NAME,
-- 										UD.DEPARTMENT_NAME AS CREATOR_DEPARTMENT_NAME,
										DOC.CLASSIFIED,
										CLSYS.SYSTEM_VALUE AS CLASSIFIED_VAL,
										ES.STATUS,
										ISNULL(A.SYSTEM_VALUE, '''') STATUS_VAL,
										ISNULL(S.REVISION, 0) REVISION,
										ISNULL(S.ITEM_CHANGED, '''') ITEM_CHANGED,
										ISNULL(S.REASON, '''') REASON,
										ISNULL(S.REFERENCE_NO, '''') REFERENCE_NO,
										ISNULL(S.SOURCE, '''') SOURCE,
										S.CREATED_DT,
										S.CREATED_BY,
										S.CHANGED_DT,
										S.CHANGED_BY,
										'''' DISTRIBUTION,
										S.DOCUMENT_TRANSACTION_ID,
										S.APPROVAL_ID APPROVAL_ID,
										ISNULL(B.SYSTEM_VALUE, '''') DOCUMENT_TYPE,
										S.PROCESS_CODE PROCESS_CODE,
										S.COMPANY_CODE COMPANY_CODE,
										S.SECTION_CODE SECTION_CODE,
										ISNULL(S.EXTERNAL_FLAG, '''') EXTERNAL_FLAG,
										CAST(S.DOCUMENT_DATE as date) DOCUMENT_DATE,
										ISNULL(S.FILE_PATH, '''') FILE_PATH,
										ISNULL(S.DELETE_FLAG, 0) DELETE_FLAG,
										S.DEPARTMENT_ID,
-- 										P.DEPARTMENT_ID AS CREATOR_DEPARTMENT_ID,
										ISNULL(S.DEPARTMENT_CODE, D.DEPARTMENT_CODE) AS DEPARTMENT_CODE,
-- 										UD.DEPARTMENT_CODE AS CREATOR_DEPARTMENT_CODE,
										S.DOCUMENT_CODE DOCUMENT_NO,
										CAST(YEAR(S.DOCUMENT_DATE) as varchar(4)) DOCUMENT_YEAR,
										S.DIVISION DIVISION,
-- 										UD.DIVISION CREATOR_DIVISION,
										ISNULL(S.DIVISION_NAME, DSYS.DIVISION_NAME) AS DIVISION_NAME,
-- 										UDSYS.SYSTEM_VALUE AS CREATOR_DIVISION_NAME,
										S.LOCATION LOCATION,
										'''' IS_APPROVED,
										S.REMARKS REMARKS,
										S.OPERATION_TYPE,
										OSYS.SYSTEM_VALUE AS OPERATION_TYPE_VAL,
										'''' ACTION,
										(SELECT TOP 1 1 FROM TB_R_PUBLISH_HISTORY WHERE DOCUMENT_CTRL_ID = S.DOCUMENT_CTRL_ID AND DEPARTMENT_ID = s.DEPARTMENT_ID) as PUBLISH_FLAG,
										DOC.NEXT_REVIEW_DATE,
										MDOC.DOCUMENT_CODE AS CATEGORY_CODE,
										MDOC.DOCUMENT_NAME AS CATEGORY_NAME,
										DOC.STATUS AS DOC_STATUS,
										ISNULL(DOCSTAT.SYSTEM_VALUE, '''') AS DOC_STATUS_VAL,
										(SELECT TOP 1 PH.CREATED_DT FROM TB_R_PUBLISH_HISTORY PH WHERE PH.DOCUMENT_CTRL_ID = S.DOCUMENT_CTRL_ID AND PH.DEPARTMENT_ID = S.DEPARTMENT_ID ORDER BY PH.CREATED_DT DESC) AS ACKNOWLEDGE_DT,
										NULL AS ACK_TOTAL,
										NULL AS ACK_DONE,
										NULL AS DIVISION_COUNT,
										NULL AS PENDING_DISTRIBUTION_COUNT
									FROM [dbo].[TB_R_CTRL_DOCUMENT] S
									CROSS APPLY (
										SELECT CASE WHEN S.OPERATION_TYPE = 2 THEN
											(SELECT TOP 1 REG.STATUS FROM TB_R_CTRL_DOCUMENT REG
											 WHERE REG.DOCUMENT_TRANSACTION_ID = S.DOCUMENT_TRANSACTION_ID
											 AND REG.OPERATION_TYPE = 1 AND ISNULL(REG.DELETE_FLAG, 0) = 0)
										ELSE S.STATUS END AS STATUS
									) ES
									JOIN TB_M_SYSTEM A
										ON A.SYSTEM_TYPE = ''DOC_CTRL_STATUS''
											AND A.SYSTEM_CODE = ES.STATUS
									JOIN TB_M_SYSTEM B
										ON B.SYSTEM_TYPE = ''DOCUMENT_TYPE''
											AND B.SYSTEM_CODE = S.DOCUMENT_TYPE
									JOIN TB_M_DEPARTMENT D
										ON D.DEPARTMENT_ID = S.DEPARTMENT_ID
									JOIN TB_R_DOCUMENT DOC
										ON DOC.DOCUMENT_CODE = S.DOCUMENT_CODE
									LEFT JOIN TB_M_DOCUMENT MDOC
										ON MDOC.DOCUMENT_ID = DOC.DOCUMENT_ID
									LEFT JOIN TB_M_SYSTEM DOCSTAT
										ON DOCSTAT.SYSTEM_TYPE = ''DOC_STATUS''
											AND DOCSTAT.SYSTEM_CODE = DOC.STATUS
									JOIN TB_M_SYSTEM CLSYS
										on CLSYS.SYSTEM_TYPE = ''CLASSIFIED''
											AND CLSYS.SYSTEM_CODE = ISNULL(DOC.CLASSIFIED, ''0'')
									JOIN TB_M_DIVISION DSYS
										on DSYS.DIVISION_CODE = ISNULL(S.DIVISION, ''0'')
									JOIN TB_M_SYSTEM OSYS
										on OSYS.SYSTEM_TYPE = ''OPERATION_TYPE''
											AND OSYS.SYSTEM_CODE = ISNULL(S.OPERATION_TYPE, ''0'')
									JOIN TB_M_USER US
										ON US.USERNAME = S.CREATED_BY
-- 									JOIN (SELECT USERNAME, MAX(POSITION_ID) POSITION_ID, MAX(DIVISION) DIVISION, MAX(DEPARTMENT_ID) DEPARTMENT_ID, MAX(SECTION_ID) SECTION_ID FROM [dbo].[TB_M_USER_POS] GROUP BY USERNAME) 
-- 									P ON US.[USERNAME] = P.[USERNAME]
-- 									JOIN TB_M_DEPARTMENT UD
-- 										ON UD.DEPARTMENT_ID = P.DEPARTMENT_ID
-- 									JOIN TB_M_SYSTEM UDSYS
-- 										on UDSYS.SYSTEM_TYPE = ''DIVISION''
-- 											AND UDSYS.SYSTEM_CODE = ISNULL(UD.DIVISION, ''0'')
									WHERE 1 = 1
									AND ISNULL(S.DELETE_FLAG, 0) = 0'	
									
									IF @DIVISION IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DIVISION LIKE ''' + REPLACE(@DIVISION , '*', '%') + ''' '
										--SET @QUERY += ' '
									END

									IF @DOCUMENT_TRANSACTION_ID IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DOCUMENT_TRANSACTION_ID LIKE ''' + REPLACE(@DOCUMENT_TRANSACTION_ID , '*', '%') + ''' '
									END
									
									IF @DOCUMENT_CODE IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DOCUMENT_CODE LIKE ''' + REPLACE(@DOCUMENT_CODE , '*', '%') + ''' '
									END
									
									IF @DOCUMENT_NAME IS NOT NULL
									BEGIN
										SET @QUERY += ' AND S.DOCUMENT_NAME LIKE ''' + REPLACE(@DOCUMENT_NAME , '*', '%') + ''' '
									END
									
									IF @YEAR IS NOT NULL
										BEGIN
										SET @QUERY += ' AND YEAR(S.DOCUMENT_DATE) = ''' + REPLACE(@YEAR , '*', '') + ''' '
									END
									
									IF @LOGIN_USER IS NOT NULL
									BEGIN
										SELECT @DIVISION_COUNT = COUNT(DIVISION) FROM TB_M_USER_POS WHERE USERNAME = @LOGIN_USER;
										SELECT @DEPARTMENT_COUNT = COUNT(DEPARTMENT_ID) FROM TB_M_USER_POS WHERE USERNAME = @LOGIN_USER;
									
										SET @QUERY += 'AND (
																	EXISTS (
																			SELECT 1 FROM TB_R_CTRL_DOCUMENT SS
																			WHERE S.OPERATION_TYPE = 2
																			AND S.CREATED_BY = ''' + @LOGIN_USER + '''
																		)';
										
										IF @DEPARTMENT_COUNT > 0
										BEGIN
											SET @QUERY += 'OR EXISTS (
																			SELECT 1 FROM TB_R_DOCUMENT_DISTRIBUTION DD
																			WHERE DD.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM TB_M_USER_POS WHERE USERNAME = '''+ @LOGIN_USER+''')
																			AND DD.DOCUMENT_TRANSACTION_ID = S.DOCUMENT_TRANSACTION_ID
																			AND DD.STATUS = 1
																			AND S.OPERATION_TYPE = 1
																		)'
										END
										ELSE
										BEGIN
											IF @DIVISION_COUNT > 0
											BEGIN
												SET @QUERY += 'OR EXISTS (
																				SELECT 1 FROM TB_R_DOCUMENT_DISTRIBUTION DD
																				WHERE DD.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM TB_M_DEPARTMENT WHERE DIVISION IN (SELECT DIVISION FROM TB_M_USER_POS WHERE USERNAME = '''+@LOGIN_USER+'''))
																				AND DD.DOCUMENT_TRANSACTION_ID = S.DOCUMENT_TRANSACTION_ID
																				AND DD.STATUS = 1
																				AND S.OPERATION_TYPE = 1
																			)'
											END
											ELSE
											BEGIN
											SET @QUERY += 'OR EXISTS (
																			SELECT 1 FROM TB_R_DOCUMENT_DISTRIBUTION DD
																			WHERE DD.DOCUMENT_TRANSACTION_ID = S.DOCUMENT_TRANSACTION_ID
																			AND DD.STATUS = 1
																			AND S.OPERATION_TYPE = 1
																		)'
											END
										END
																		
										SET @QUERY += ') ';
								END

	SET @QUERY += ' 									
								)
								SELECT * FROM data
								WHERE 1 = 1 '
	
	IF (@PageSize IS NOT NULL AND @PageSize > 0) AND @PageNumber IS NOT NULL 
	BEGIN
		SET @QUERY += ' AND RowNumber > '+ CAST((@PageSize * (@PageNumber - 1)) AS VARCHAR) +' AND RowNumber <= ' +CAST(@PageSize + (@PageSize * (@PageNumber - 1)) AS VARCHAR);
	END
	EXEC(@QUERY)
	
END
GO
