SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_User_GetByKey]
  @USERNAME varchar(30)
AS
BEGIN

  DECLARE @QUERY VARCHAR(MAX)

	SET @QUERY = 'SELECT
								A.USERNAME,
								A.REG_NO,
								A.FULL_NAME,
								A.PASSWORD,
								A.PASSWORD AS CONFIRM_PASSWORD,
								A.PASSWORD AS OLD_PASSWORD,
								A.EMAIL,
								A.PHONE,
								A.ROLE_ID,
								B.ROLE_NAME,
								P.POSITION_ID,
								O.POSITION_NAME,
								P.DIVISION,
								Y.DIVISION_NAME,
								P.DEPARTMENT_ID,
								D.DEPARTMENT_CODE,
								D.DEPARTMENT_NAME,
								P.SECTION_ID,
								S.SECTION_CODE,
								S.SECTION_NAME,
								(SELECT TOP 1 DOCUMENT_CONTROL_ACCESS FROM TB_M_DEPARTMENT MD LEFT JOIN TB_M_USER_POS MP ON MD.DIVISION = MP.DIVISION WHERE MP.USERNAME = A.USERNAME ORDER BY DOCUMENT_CONTROL_ACCESS DESC) AS DOCUMENT_CONTROL_ACCESS,
								A.FILE_PATH,
								A.SIGNATURE_PATH,
								A.AD_USER,
								A.CREATED_DT,
								A.CREATED_BY,
								A.CHANGED_DT,
								A.CHANGED_BY
							FROM [dbo].[TB_M_USER] A
							LEFT JOIN (SELECT USERNAME, MAX(POSITION_ID) POSITION_ID, MAX(DIVISION) DIVISION, MAX(DEPARTMENT_ID) DEPARTMENT_ID, MAX(SECTION_ID) SECTION_ID FROM [dbo].[TB_M_USER_POS] GROUP BY USERNAME)
									P ON A.[USERNAME] = P.[USERNAME]
									LEFT JOIN [dbo].[TB_M_ROLE] B ON A.[ROLE_ID] = B.[ROLE_ID]
									LEFT JOIN [dbo].[TB_M_POSITION] O ON P.[POSITION_ID] = O.[POSITION_ID]
									LEFT JOIN [dbo].[TB_M_DEPARTMENT] D ON D.[DEPARTMENT_ID] = P.[DEPARTMENT_ID]
									LEFT JOIN [dbo].[TB_M_SECTION] S ON S.[SECTION_ID] = P.[SECTION_ID]
									LEFT JOIN [dbo].[TB_M_DIVISION] Y ON Y.[DIVISION_CODE] = P.[DIVISION]
							WHERE 1 = 1
							AND ISNULL(A.DELETE_FLAG, ''0'') <> ''1'' '

	IF @USERNAME IS NOT NULL
	BEGIN
		SET @QUERY += ' AND A.USERNAME LIKE ''' + REPLACE(@USERNAME , '*', '%') + ''' '
	END

	EXEC(@QUERY)

END
GO
