SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_UserPosition_Delete]
	@USERNAME VARCHAR(50),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	
	BEGIN
	DELETE FROM [dbo].[TB_M_USER_POS]
	WHERE USERNAME = @USERNAME
	
	SET @RETURN_MSG = 'Successfully Delete Data'
	END
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
