-- Assigns (or clears, when @FOLDER_ID is NULL) one document's PERSONAL folder
-- for @USERNAME - upserts TB_R_DOCUMENT_FOLDER_PERSONAL (DOCUMENT_TRANSACTION_ID,
-- USERNAME) unique pair. Clearing deletes the row rather than storing
-- FOLDER_ID = NULL, so presence of a row always means "this user filed this
-- document somewhere" (mirrors sp_DocumentControlDashboard_AssignFolder's single-
-- row-per-call convention, called once per document from the controller).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_UserDashboard_AssignFolder]
	@DOCUMENT_TRANSACTION_ID	INT,
	@USERNAME					VARCHAR(255),
	@FOLDER_ID					INT,
	@RETURN_MSG					VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_UserDashboard_AssignFolder';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'My Documents', 'Assign Personal Folder', @LOCATION, @USERNAME

	IF @FOLDER_ID IS NOT NULL AND NOT EXISTS (
		SELECT 1 FROM [dbo].[TB_M_DOCUMENT_FOLDER_PERSONAL] WHERE FOLDER_ID = @FOLDER_ID AND USERNAME = @USERNAME AND ISNULL(DELETE_FLAG, 0) = 0
	)
	BEGIN
		SET @RETURN_MSG = 'ERROR: Folder not found';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @USERNAME
		RETURN 0;
	END

	IF @FOLDER_ID IS NULL
	BEGIN
		DELETE FROM [dbo].[TB_R_DOCUMENT_FOLDER_PERSONAL]
		WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND USERNAME = @USERNAME
	END
	ELSE IF EXISTS (
		SELECT 1 FROM [dbo].[TB_R_DOCUMENT_FOLDER_PERSONAL]
		WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND USERNAME = @USERNAME
	)
	BEGIN
		UPDATE [dbo].[TB_R_DOCUMENT_FOLDER_PERSONAL]
		SET FOLDER_ID	= @FOLDER_ID,
				CHANGED_DT	= GETDATE(),
				CHANGED_BY	= @USERNAME
		WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND USERNAME = @USERNAME
	END
	ELSE
	BEGIN
		INSERT INTO [dbo].[TB_R_DOCUMENT_FOLDER_PERSONAL] (
			DOCUMENT_TRANSACTION_ID, USERNAME, FOLDER_ID, CREATED_DT, CREATED_BY, CHANGED_DT, CHANGED_BY
		) VALUES (
			@DOCUMENT_TRANSACTION_ID, @USERNAME, @FOLDER_ID, GETDATE(), @USERNAME, GETDATE(), @USERNAME
		)
	END

	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @USERNAME
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @USERNAME
	RETURN 0;
END CATCH
GO
