SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_UserDashboard_Request]
		@DOCUMENT_TRANSACTION_ID int,
		@CREATED_BY varchar(50),
		@CHANGED_BY varchar(50),
		@RETURN_MSG 				VARCHAR(MAX) OUTPUT,
		@RETURN_ID	 		VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @PROCESS_ID BIGINT
	DECLARE @DIVISION_COUNT INT
	DECLARE @DEPARTMENT_COUNT INT
	
	, @LOCATION VARCHAR(255) = 'sp_UserDashboard_Request'
	, @rev_DOCUMENT_ID int
	, @rev_REVISION int
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'User Dashboard', 'Request Document', @LOCATION, @CREATED_BY
	
	SELECT @DEPARTMENT_COUNT = COUNT(DEPARTMENT_ID) FROM TB_M_USER_POS WHERE USERNAME = @CREATED_BY;

	IF ISNULL(@CREATED_BY, '') <> ''
		BEGIN
		
		IF @DEPARTMENT_COUNT > 0
		BEGIN
			BEGIN
				IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_R_DOCUMENT_DISTRIBUTION] 
				WHERE [DOCUMENT_TRANSACTION_ID] = @DOCUMENT_TRANSACTION_ID
				AND [DEPARTMENT_ID] IN (SELECT DEPARTMENT_ID FROM TB_M_USER_POS WHERE USERNAME = @CREATED_BY))
				BEGIN
						SET @RETURN_ID = 0;
						SET @RETURN_MSG = 'ERROR: Selected Document No is already distributed' ;
						EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
						RETURN 0;
				END
			END
		END
	END
	
	IF ISNULL(@CREATED_BY, '') <> ''
	BEGIN
		SELECT @DIVISION_COUNT = COUNT(DIVISION) FROM TB_M_USER_POS WHERE USERNAME = @CREATED_BY;
		
		IF @DIVISION_COUNT > 0 AND @DEPARTMENT_COUNT = 0
			BEGIN
				IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_R_DOCUMENT_DISTRIBUTION] 
				WHERE [DOCUMENT_TRANSACTION_ID] = @DOCUMENT_TRANSACTION_ID
				AND [DEPARTMENT_ID] IN (SELECT DEPARTMENT_ID FROM TB_M_DEPARTMENT WHERE DIVISION IN (SELECT DIVISION FROM TB_M_USER_POS WHERE USERNAME = @CREATED_BY)))
				BEGIN
						SET @RETURN_ID = 0;
						SET @RETURN_MSG = 'ERROR: Selected Document No is already distributed' ;
						EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
						RETURN 0;
				END
			END
	 END						
	
	IF EXISTS(
		SELECT 1
		FROM TB_R_CTRL_DOCUMENT
		WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND DELETE_FLAG != '1'
		AND OPERATION_TYPE = 2
		AND CREATED_BY = @CREATED_BY
	)
	BEGIN
		SET @RETURN_ID = 0;
		SET @RETURN_MSG = 'ERROR: Selected Document No is already requested';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
		RETURN 0;
	END

	INSERT INTO [dbo].[TB_R_CTRL_DOCUMENT]
           ([DOCUMENT_CODE]
           ,[DOCUMENT_NAME]
           ,[DOCUMENT_TYPE]
           ,[PROCESS_CODE]
           ,[COMPANY_CODE]
           ,[SECTION_CODE]
           ,[ITEM_CHANGED]
           ,[REASON]
           ,[EXTERNAL_FLAG]
           ,[REFERENCE_NO]
           ,[SOURCE]
           ,[DOCUMENT_DATE]
           ,[FILE_PATH]
           ,[STATUS]
           ,[REVISION]
           ,[APPROVAL_ID]
           ,[DELETE_FLAG]
           ,[DEPARTMENT_ID]
           ,[DIVISION]
           ,[OPERATION_TYPE]
           ,[DOCUMENT_TRANSACTION_ID]
           ,[CREATED_BY]
           ,[CREATED_DT]
           ,[CHANGED_BY]
           ,[CHANGED_DT])
     SELECT [DOCUMENT_CODE]
           ,[DOCUMENT_NAME]
           ,[DOCUMENT_TYPE]
           ,[PROCESS_CODE]
           ,[COMPANY_CODE]
           ,[SECTION_CODE]
           ,[ITEM_CHANGED]
           ,[REASON]
           ,[EXTERNAL_FLAG]
           ,[REFERENCE_NO]
           ,[SOURCE]
           ,[DOCUMENT_DATE]
           ,[FILE_PATH]
           ,'0'[STATUS]
           ,[REVISION]
           ,[APPROVAL_ID]
           ,[DELETE_FLAG]
           ,[DEPARTMENT_ID]
           ,[DIVISION]
           ,2
					 ,[DOCUMENT_TRANSACTION_ID]
           ,@CREATED_BY [CREATED_BY]
           ,GETDATE() [CREATED_DT]
           ,@CREATED_BY [CHANGED_BY]
           ,GETDATE() [CHANGED_DT]
	FROM TB_R_CTRL_DOCUMENT
	WHERE DOCUMENT_TRANSACTION_ID = @DOCUMENT_TRANSACTION_ID AND OPERATION_TYPE = '1' AND DELETE_FLAG != '1'

	SET @RETURN_ID = SCOPE_IDENTITY();
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @CREATED_BY
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_ID = 0;
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @CREATED_BY
	RETURN 0;
END CATCH
GO
