SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_User_RemoveAttachment]
	@USERNAME		 			    VARCHAR(50),
	@LOGIN_USER 					VARCHAR(255),
	@RETURN_MSG 					VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	UPDATE [dbo].[TB_M_USER]
	SET FILE_PATH  = null,
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE USERNAME = @USERNAME
	
	SET @RETURN_MSG = 'Successfully Save Data'
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	RETURN 0;
END CATCH
GO
