SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_User_UpdateSignature]
	@USERNAME VARCHAR(255),
	@SIGNATURE_PATH VARCHAR(255),
	@LOGIN_USER VARCHAR(255),
	@RETURN_MSG VARCHAR(MAX) OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_User_UpdateSignature';

	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'User Profile', 'Update Signature', @LOCATION, @LOGIN_USER

	IF @USERNAME IS NULL OR LEN(@USERNAME) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Username should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END

	UPDATE [dbo].[TB_M_USER]
	SET SIGNATURE_PATH = @SIGNATURE_PATH,
			CHANGED_DT = GETDATE(),
			CHANGED_BY = @LOGIN_USER
	WHERE USERNAME = @USERNAME

	SET @RETURN_MSG = 'Successfully Save Signature'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
