SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_UserPosition_GetByUsername]
  @USERNAME varchar(30)
AS
BEGIN

  DECLARE @QUERY VARCHAR(MAX)
	
	SET @QUERY = 'SELECT
								U.USER_POS_ID,
								U.USERNAME,
								U.POSITION_ID,
								P.POSITION_NAME AS POSITION_NAME,
								U.DIVISION,
								S.DIVISION_NAME,
								U.DEPARTMENT_ID,
								D.DEPARTMENT_NAME AS DEPARTMENT_NAME,
								U.SECTION_ID,
								SC.SECTION_NAME AS SECTION_NAME,
								DV.DOCUMENT_CONTROL_ACCESS
							FROM TB_M_USER_POS U
							LEFT JOIN TB_M_POSITION P ON P.POSITION_ID = U.POSITION_ID
							LEFT JOIN TB_M_DIVISION S ON S.DIVISION_CODE = U.DIVISION
							LEFT JOIN TB_M_DEPARTMENT D ON D.DEPARTMENT_ID = U.DEPARTMENT_ID
							LEFT JOIN TB_M_SECTION SC ON SC.SECTION_ID = U.SECTION_ID
							LEFT JOIN TB_M_DEPARTMENT DV ON DV.DIVISION = U.DIVISION
							WHERE 1 = 1 '
							
	IF @USERNAME IS NOT NULL
	BEGIN
		SET @QUERY += ' AND U.USERNAME LIKE ''' + REPLACE(@USERNAME , '*', '%') + ''' '
	END
	
	EXEC(@QUERY)

END
GO
