SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Workflow_DocInsertHeader]
  @DOCUMENT_LEVEL 	INT,
	@CREATOR_LEVEL 		INT,
	@LOGIN_USER 			VARCHAR(255),
	@RETURN_MSG 			VARCHAR(MAX) OUTPUT,
	@RETURN_ID				INT OUTPUT
AS
BEGIN TRY

	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Workflow_DocInsertHeader';
	
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Workflow Document Header', 'Insert', @LOCATION, @LOGIN_USER

	IF @DOCUMENT_LEVEL IS NULL OR LEN(@DOCUMENT_LEVEL) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Document Level should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		RETURN 0;
	END
	
	IF @CREATOR_LEVEL IS NULL OR LEN(@CREATOR_LEVEL) < 1
	BEGIN
		SET @RETURN_MSG = 'ERROR: Creator Level should not be null';
		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
		SET @RETURN_ID = 0;
		RETURN 0;
	END	
	
-- 	IF EXISTS (SELECT TOP 1 1 FROM [dbo].[TB_M_WORKFLOW_DOC_H] WHERE @DOCUMENT_LEVEL = @DOCUMENT_LEVEL)
-- 	BEGIN
-- 		SET @RETURN_MSG = 'ERROR: Workflow Document already exist. (Workflow Document: "' + @DOCUMENT_LEVEL+ '")';
-- 		EXEC sp_WriteLog @PROCESS_ID, '3', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
-- 		SET @RETURN_ID = 0;
-- 		RETURN 0;
-- 	END
	
	INSERT INTO [dbo].[TB_M_WORKFLOW_DOC_H] (
		DOCUMENT_LEVEL,
		CREATOR_LEVEL,
		CREATED_DT,
		CREATED_BY,
		CHANGED_DT,
		CHANGED_BY
	) VALUES (
		@DOCUMENT_LEVEL,
		@CREATOR_LEVEL,
		GETDATE(),
		@LOGIN_USER,
		GETDATE(),
		@LOGIN_USER
	)
	
	IF @@ROWCOUNT > 0 
	BEGIN
		DECLARE @workflowId INT;
		SET @workflowId = SCOPE_IDENTITY();
		
		SET @RETURN_ID = @workflowId;
	END
	
	SET @RETURN_MSG = 'Successfully Save Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
	
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	SET @RETURN_ID = 0;
	RETURN 0;
END CATCH
GO
