CREATE OR ALTER PROCEDURE [dbo].[sp_Workflow_DocDelete]
	@WORKFLOW_DOC_ID INT,
	@LOGIN_USER 		 VARCHAR(255),
	@RETURN_MSG 		 VARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	SET NOCOUNT ON;
	
	DECLARE @PROCESS_ID BIGINT,
					@LOCATION VARCHAR(255) = 'sp_Workflow_DocDelete';
					
	EXEC sp_StartLog @PROCESS_ID OUTPUT, 'Workflow Document Master', 'Delete', @LOCATION, @LOGIN_USER	
	
	DELETE FROM [dbo].[TB_M_WORKFLOW_DOC_H]
	WHERE WORKFLOW_DOC_ID = @WORKFLOW_DOC_ID
	
	DELETE FROM [dbo].[TB_M_WORKFLOW_DOC_D]
	WHERE WORKFLOW_DOC_ID = @WORKFLOW_DOC_ID
	
	SET @RETURN_MSG = 'Successfully Delete Data'
	EXEC sp_WriteLog @PROCESS_ID, '2', 'INF', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 1;
	
END TRY
BEGIN CATCH
	SET @RETURN_MSG = 'ERROR: ' + ERROR_PROCEDURE() +': '+ ERROR_MESSAGE() + ', at line = ' +  CAST(ERROR_LINE() AS VARCHAR);
	EXEC sp_WriteLog @PROCESS_ID, '4', 'ERR', @RETURN_MSG, @LOCATION, @LOGIN_USER
	RETURN 0;
END CATCH
GO
