CREATE OR ALTER PROCEDURE [dbo].[sp_Workflow_DocGetByName]
	@DOCUMENT_LEVEL  	INT
AS
BEGIN  

	DECLARE @QUERY VARCHAR(MAX)
	
	SET @QUERY = 'SELECT 
									CAST(W.WORKFLOW_DOC_ID AS INT) AS WORKFLOW_DOC_ID,
									H.DOCUMENT_LEVEL,
									H.CREATOR_LEVEL,
									CAST(W.WORKFLOW_SEQ AS INT) AS WORKFLOW_SEQ,
									W.POSITION_ID,
									U.POSITION_NAME AS POSITION_NAME,
									W.CREATED_DT,
									W.CREATED_BY,
									W.CHANGED_DT,
									W.CHANGED_BY
								FROM [dbo].[TB_M_WORKFLOW_DOC_D] W
								JOIN [dbo].[TB_M_WORKFLOW_DOC_H] H ON H.WORKFLOW_DOC_ID = W.WORKFLOW_DOC_ID
								JOIN [dbo].[TB_M_POSITION] U ON W.POSITION_ID = U.POSITION_ID
								WHERE 1 = 1 '
								
	IF @DOCUMENT_LEVEL IS NOT NULL
	BEGIN
		SET @QUERY += ' AND H.DOCUMENT_LEVEL LIKE ''' + REPLACE(@DOCUMENT_LEVEL , '*', '%') + ''' '
	END
	
	SET @QUERY += ' ORDER BY W.WORKFLOW_SEQ ASC'
	
	EXEC(@QUERY)
	
END
GO
