-- Lanjutan Maintenance_ResetTransactionData_20260828.sql: Bagian 2 & 3 saja.
-- Backup (Bagian 1) sudah sukses jalan sebelumnya - JANGAN dijalankan ulang.
-- SET eksplisit di bawah ini untuk menghindari error Msg 1934 (QUOTED_IDENTIFIER)
-- yang muncul saat file dijalankan lewat sqlcmd -i.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

-- Copy Request: PRINT_LOG -> D -> H
TRUNCATE TABLE TB_R_COPY_REQUEST_PRINT_LOG;
DELETE FROM TB_R_COPY_REQUEST_D;
DBCC CHECKIDENT ('TB_R_COPY_REQUEST_D', RESEED, 0);
DELETE FROM TB_R_COPY_REQUEST_H;
DBCC CHECKIDENT ('TB_R_COPY_REQUEST_H', RESEED, 0);

-- Document Submission Form: D -> H
TRUNCATE TABLE TB_R_DOC_SUBMISSION_FORM_D;
DELETE FROM TB_R_DOC_SUBMISSION_FORM_H;
DBCC CHECKIDENT ('TB_R_DOC_SUBMISSION_FORM_H', RESEED, 0);

TRUNCATE TABLE TB_R_LOG_D;
TRUNCATE TABLE TB_R_LOG_H;
TRUNCATE TABLE TB_R_APPROVAL_D;
TRUNCATE TABLE TB_R_APPROVAL_H;
TRUNCATE TABLE TB_R_APPROVAL_REASSIGN_LOG;
TRUNCATE TABLE TB_R_DOCUMENT_DISTRIBUTION;
TRUNCATE TABLE TB_R_PUBLISH_HISTORY;
TRUNCATE TABLE TB_R_DOCUMENT_HISTORY;
TRUNCATE TABLE TB_R_DOCUMENT_LOG;

-- Related Division -> Document
TRUNCATE TABLE TB_R_DOCUMENT_RELATED_DIVISION;
TRUNCATE TABLE TB_R_CTRL_DOCUMENT;
DELETE FROM TB_R_DOCUMENT;
DBCC CHECKIDENT ('TB_R_DOCUMENT', RESEED, 0);

TRUNCATE TABLE TB_R_NOTIFICATION;
TRUNCATE TABLE TB_M_EXTERNAL_DOCUMENT;
GO

UPDATE TB_M_SEQUENCE
SET SEQ_NO = 0,
	CHANGED_BY = 'dms.admin',
	CHANGED_DT = GETDATE()
WHERE SEQ_NO <> 0;
GO
