-- =====================================================================
-- Maintenance: reset semua data transaksi + nomor urut dokumen ke awal,
-- untuk mulai testing/UAT dari kondisi bersih (2026-08-28).
--
-- Turunan dari SQL/Maintenance_ResetTransactionData_20260810.sql, dengan
-- tabel tambahan yang lahir setelah 2026-08-10 (Copy Request, Related
-- Division) dan penyesuaian urutan karena FK constraint baru:
--   - FK_CPR_D_REQUEST: TB_R_COPY_REQUEST_D -> TB_R_COPY_REQUEST_H
--   - FK_CPR_PRINTLOG_REQUEST_DETAIL: TB_R_COPY_REQUEST_PRINT_LOG -> TB_R_COPY_REQUEST_D
--   - FK_DOC_RELATED_DIVISION_DOCUMENT: TB_R_DOCUMENT_RELATED_DIVISION -> TB_R_DOCUMENT
-- Ketiga tabel yang DIREFERENSIKAN FK di atas (COPY_REQUEST_H,
-- COPY_REQUEST_D, TB_R_DOCUMENT) tidak bisa di-TRUNCATE selama FK
-- constraint-nya masih ada (walau isinya kosong) - sama seperti
-- TB_R_DOC_SUBMISSION_FORM_H dulu. Makanya keempatnya pakai
-- DELETE + DBCC CHECKIDENT manual, bukan TRUNCATE.
--
-- Backup diambil dulu (SELECT INTO ..._BACKUP_20260828) sebelum
-- data dihapus, supaya masih bisa dipulihkan kalau ternyata perlu.
-- Backup lama (_BACKUP_20260810/16/16b/16c/18/19/26) TIDAK disentuh.
--
-- Skrip sekali-jalan - jangan dijalankan ulang tanpa sadar.
-- Jalankan di database DMS_NEW
-- =====================================================================

-- ---------------------------------------------------------------------
-- Bagian 1: Backup
-- ---------------------------------------------------------------------
SELECT * INTO TB_R_DOCUMENT_BACKUP_20260828 FROM TB_R_DOCUMENT;
SELECT * INTO TB_R_CTRL_DOCUMENT_BACKUP_20260828 FROM TB_R_CTRL_DOCUMENT;
SELECT * INTO TB_R_DOCUMENT_DISTRIBUTION_BACKUP_20260828 FROM TB_R_DOCUMENT_DISTRIBUTION;
SELECT * INTO TB_R_DOCUMENT_LOG_BACKUP_20260828 FROM TB_R_DOCUMENT_LOG;
SELECT * INTO TB_R_DOCUMENT_HISTORY_BACKUP_20260828 FROM TB_R_DOCUMENT_HISTORY;
SELECT * INTO TB_R_DOCUMENT_RELATED_DIVISION_BACKUP_20260828 FROM TB_R_DOCUMENT_RELATED_DIVISION;
SELECT * INTO TB_R_PUBLISH_HISTORY_BACKUP_20260828 FROM TB_R_PUBLISH_HISTORY;
SELECT * INTO TB_R_APPROVAL_H_BACKUP_20260828 FROM TB_R_APPROVAL_H;
SELECT * INTO TB_R_APPROVAL_D_BACKUP_20260828 FROM TB_R_APPROVAL_D;
SELECT * INTO TB_R_APPROVAL_REASSIGN_LOG_BACKUP_20260828 FROM TB_R_APPROVAL_REASSIGN_LOG;
SELECT * INTO TB_R_DOC_SUBMISSION_FORM_H_BACKUP_20260828 FROM TB_R_DOC_SUBMISSION_FORM_H;
SELECT * INTO TB_R_DOC_SUBMISSION_FORM_D_BACKUP_20260828 FROM TB_R_DOC_SUBMISSION_FORM_D;
SELECT * INTO TB_R_COPY_REQUEST_H_BACKUP_20260828 FROM TB_R_COPY_REQUEST_H;
SELECT * INTO TB_R_COPY_REQUEST_D_BACKUP_20260828 FROM TB_R_COPY_REQUEST_D;
SELECT * INTO TB_R_COPY_REQUEST_PRINT_LOG_BACKUP_20260828 FROM TB_R_COPY_REQUEST_PRINT_LOG;
SELECT * INTO TB_R_NOTIFICATION_BACKUP_20260828 FROM TB_R_NOTIFICATION;
SELECT * INTO TB_R_LOG_H_BACKUP_20260828 FROM TB_R_LOG_H;
SELECT * INTO TB_R_LOG_D_BACKUP_20260828 FROM TB_R_LOG_D;
SELECT * INTO TB_M_EXTERNAL_DOCUMENT_BACKUP_20260828 FROM TB_M_EXTERNAL_DOCUMENT;
GO

-- ---------------------------------------------------------------------
-- Bagian 2: Hapus data (child sebelum parent utk yang ada FK)
-- ---------------------------------------------------------------------

-- Copy Request: PRINT_LOG -> D -> H
TRUNCATE TABLE TB_R_COPY_REQUEST_PRINT_LOG;
DELETE FROM TB_R_COPY_REQUEST_D;
DBCC CHECKIDENT ('TB_R_COPY_REQUEST_D', RESEED, 0);
DELETE FROM TB_R_COPY_REQUEST_H;
DBCC CHECKIDENT ('TB_R_COPY_REQUEST_H', RESEED, 0);

-- Document Submission Form: D -> H
TRUNCATE TABLE TB_R_DOC_SUBMISSION_FORM_D;
DELETE FROM TB_R_DOC_SUBMISSION_FORM_H;
DBCC CHECKIDENT ('TB_R_DOC_SUBMISSION_FORM_H', RESEED, 0);

TRUNCATE TABLE TB_R_LOG_D;
TRUNCATE TABLE TB_R_LOG_H;
TRUNCATE TABLE TB_R_APPROVAL_D;
TRUNCATE TABLE TB_R_APPROVAL_H;
TRUNCATE TABLE TB_R_APPROVAL_REASSIGN_LOG;
TRUNCATE TABLE TB_R_DOCUMENT_DISTRIBUTION;
TRUNCATE TABLE TB_R_PUBLISH_HISTORY;
TRUNCATE TABLE TB_R_DOCUMENT_HISTORY;
TRUNCATE TABLE TB_R_DOCUMENT_LOG;

-- Related Division -> Document
TRUNCATE TABLE TB_R_DOCUMENT_RELATED_DIVISION;
TRUNCATE TABLE TB_R_CTRL_DOCUMENT;
DELETE FROM TB_R_DOCUMENT;
DBCC CHECKIDENT ('TB_R_DOCUMENT', RESEED, 0);

TRUNCATE TABLE TB_R_NOTIFICATION;
TRUNCATE TABLE TB_M_EXTERNAL_DOCUMENT;
GO

-- ---------------------------------------------------------------------
-- Bagian 3: Reset nomor urut dokumen (TB_M_SEQUENCE) balik ke 0
-- ---------------------------------------------------------------------
UPDATE TB_M_SEQUENCE
SET SEQ_NO = 0,
	CHANGED_BY = 'dms.admin',
	CHANGED_DT = GETDATE()
WHERE SEQ_NO <> 0;
GO
