-- =====================================================================
-- Snapshot nama Division/Department/Section ke tabel transaksi (request
-- Hendra 2026-08-22).
--
-- Masalah: DIVISION_NAME/DEPARTMENT_NAME/SECTION_NAME cuma tersimpan di
-- tabel master (TB_M_DIVISION/TB_M_DEPARTMENT/TB_M_SECTION). Semua tabel
-- transaksi cuma simpan kode/ID, nama diambil lewat JOIN live ke master
-- tiap kali ditampilkan/dicetak - jadi rename nama di Master otomatis
-- mengubah tampilan SEMUA dokumen lama (termasuk yang sudah dicetak/
-- diarsipkan). Division Code sendiri sudah readonly saat Edit, jadi aman
-- dipakai sebagai kunci; masalahnya murni di NAME.
--
-- Fix: tambah kolom snapshot di tabel transaksi, diisi SEKALI saat record
-- dibuat (lihat perubahan di masing-masing sp_..._Insert / SupersedeRevision/
-- dst di SQL/StoredProcedures/). SP baca (Search/GetByKey) diubah pakai
-- ISNULL(snapshot, live-join) supaya baris lama (snapshot masih NULL,
-- termasuk 3 baris dev existing) tetap tampil normal dari master sampai
-- direvisi/dibuat ulang.
--
-- Kolom sengaja diberi nama SAMA PERSIS dengan alias yang sudah dipakai SP
-- (DIVISION_NAME/DEPARTMENT_CODE/DEPARTMENT_NAME/SECTION_NAME) - properti
-- C# yang bersangkutan SUDAH ADA di model (bukan [NotMapped], dicek satu
-- per satu), jadi TIDAK ADA perubahan C#/View/export yang diperlukan sama
-- sekali. Lihat SQL/StoredProcedures/*.sql untuk perubahan baca/tulisnya.
--
-- Idempotent (guard pakai COL_LENGTH sebelum ADD COLUMN). Jalankan di
-- database DMS_NEW.
-- =====================================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ---------- TB_R_DOCUMENT ----------
IF COL_LENGTH('TB_R_DOCUMENT', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT] ADD DIVISION_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_DOCUMENT', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_R_DOCUMENT', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_DOCUMENT', 'SECTION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT] ADD SECTION_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_R_DOCUMENT_HISTORY ----------
IF COL_LENGTH('TB_R_DOCUMENT_HISTORY', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_HISTORY] ADD DIVISION_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_DOCUMENT_HISTORY', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_HISTORY] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_R_DOCUMENT_HISTORY', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_HISTORY] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_DOCUMENT_HISTORY', 'SECTION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_HISTORY] ADD SECTION_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_R_CTRL_DOCUMENT ----------
-- TIDAK ada SECTION_NAME - DocumentControlMaintenance.cs tidak punya properti
-- itu dan P4D/UserDashboard tidak pernah menampilkan Section, jadi tidak perlu.
IF COL_LENGTH('TB_R_CTRL_DOCUMENT', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_CTRL_DOCUMENT] ADD DIVISION_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_CTRL_DOCUMENT', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_R_CTRL_DOCUMENT] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_R_CTRL_DOCUMENT', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_CTRL_DOCUMENT] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_R_COPY_REQUEST_H ----------
IF COL_LENGTH('TB_R_COPY_REQUEST_H', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_COPY_REQUEST_H] ADD DIVISION_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_COPY_REQUEST_H', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_R_COPY_REQUEST_H] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_R_COPY_REQUEST_H', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_COPY_REQUEST_H] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_COPY_REQUEST_H', 'SECTION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_COPY_REQUEST_H] ADD SECTION_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_R_DOC_SUBMISSION_FORM_H ----------
IF COL_LENGTH('TB_R_DOC_SUBMISSION_FORM_H', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOC_SUBMISSION_FORM_H] ADD DIVISION_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_DOC_SUBMISSION_FORM_H', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_R_DOC_SUBMISSION_FORM_H] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_R_DOC_SUBMISSION_FORM_H', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOC_SUBMISSION_FORM_H] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_DOC_SUBMISSION_FORM_H', 'SECTION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOC_SUBMISSION_FORM_H] ADD SECTION_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_M_EXTERNAL_DOCUMENT ----------
-- Tanpa Section - modul ini tidak punya field Section sama sekali.
IF COL_LENGTH('TB_M_EXTERNAL_DOCUMENT', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_M_EXTERNAL_DOCUMENT] ADD DIVISION_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_M_EXTERNAL_DOCUMENT', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_M_EXTERNAL_DOCUMENT] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_M_EXTERNAL_DOCUMENT', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_M_EXTERNAL_DOCUMENT] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_R_DOCUMENT_RELATED_DIVISION ----------
-- DIVISION_NAME properti sudah ada di DocumentRelatedDivision.cs (dipetakan
-- sengaja meski awalnya bukan kolom fisik - lihat komentar di model). Sekarang
-- jadi kolom fisik sungguhan untuk snapshot.
IF COL_LENGTH('TB_R_DOCUMENT_RELATED_DIVISION', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_RELATED_DIVISION] ADD DIVISION_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_R_DOCUMENT_DISTRIBUTION ----------
-- Modul ini sebelumnya TIDAK menyimpan divisi sama sekali (diturunkan
-- transitif dari department master tiap query) - sekarang ditambah semua.
IF COL_LENGTH('TB_R_DOCUMENT_DISTRIBUTION', 'DIVISION') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_DISTRIBUTION] ADD DIVISION VARCHAR(50) NULL;
IF COL_LENGTH('TB_R_DOCUMENT_DISTRIBUTION', 'DIVISION_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_DISTRIBUTION] ADD DIVISION_NAME VARCHAR(255) NULL;
IF COL_LENGTH('TB_R_DOCUMENT_DISTRIBUTION', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_DISTRIBUTION] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_R_DOCUMENT_DISTRIBUTION', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_DOCUMENT_DISTRIBUTION] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
GO

-- ---------- TB_R_PUBLISH_HISTORY ----------
IF COL_LENGTH('TB_R_PUBLISH_HISTORY', 'DEPARTMENT_CODE') IS NULL
	ALTER TABLE [dbo].[TB_R_PUBLISH_HISTORY] ADD DEPARTMENT_CODE VARCHAR(5) NULL;
IF COL_LENGTH('TB_R_PUBLISH_HISTORY', 'DEPARTMENT_NAME') IS NULL
	ALTER TABLE [dbo].[TB_R_PUBLISH_HISTORY] ADD DEPARTMENT_NAME VARCHAR(255) NULL;
GO

-- =====================================================================
-- Backfill baris lama dari master (sekali jalan, aman diulang - hanya
-- menyentuh baris yang snapshot-nya masih NULL). Data dev saat ini nyaris
-- kosong, tapi tetap ditulis benar untuk dipakai di data produksi nanti.
-- =====================================================================

UPDATE R SET
	R.DIVISION_NAME = DIV.DIVISION_NAME,
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME,
	R.SECTION_NAME = SEC.SECTION_NAME
FROM [dbo].[TB_R_DOCUMENT] R
LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = R.DIVISION
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT
LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = R.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
WHERE R.DIVISION_NAME IS NULL AND R.DEPARTMENT_NAME IS NULL AND R.SECTION_NAME IS NULL;

UPDATE R SET
	R.DIVISION_NAME = DIV.DIVISION_NAME,
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME,
	R.SECTION_NAME = SEC.SECTION_NAME
FROM [dbo].[TB_R_DOCUMENT_HISTORY] R
LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = R.DIVISION
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT
LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = R.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
WHERE R.DIVISION_NAME IS NULL AND R.DEPARTMENT_NAME IS NULL AND R.SECTION_NAME IS NULL;

UPDATE R SET
	R.DIVISION_NAME = DIV.DIVISION_NAME,
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME
FROM [dbo].[TB_R_CTRL_DOCUMENT] R
LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = ISNULL(R.DIVISION, '0')
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT_ID
WHERE R.DIVISION_NAME IS NULL AND R.DEPARTMENT_NAME IS NULL;

UPDATE R SET
	R.DIVISION_NAME = DIV.DIVISION_NAME,
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME,
	R.SECTION_NAME = SEC.SECTION_NAME
FROM [dbo].[TB_R_COPY_REQUEST_H] R
LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = R.DIVISION
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT_ID
LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = R.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
WHERE R.DIVISION_NAME IS NULL AND R.DEPARTMENT_NAME IS NULL;

UPDATE R SET
	R.DIVISION_NAME = DIV.DIVISION_NAME,
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME,
	R.SECTION_NAME = SEC.SECTION_NAME
FROM [dbo].[TB_R_DOC_SUBMISSION_FORM_H] R
LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = R.DIVISION
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT_ID
LEFT JOIN [dbo].[TB_M_SECTION] SEC ON SEC.SECTION_CODE = R.SECTION_CODE AND SEC.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE
WHERE R.DIVISION_NAME IS NULL AND R.DEPARTMENT_NAME IS NULL;

UPDATE R SET
	R.DIVISION_NAME = DIV.DIVISION_NAME,
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME
FROM [dbo].[TB_M_EXTERNAL_DOCUMENT] R
LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = R.DIVISION
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT_ID
WHERE R.DIVISION_NAME IS NULL AND R.DEPARTMENT_NAME IS NULL;

UPDATE R SET
	R.DIVISION_NAME = DIV.DIVISION_NAME
FROM [dbo].[TB_R_DOCUMENT_RELATED_DIVISION] R
LEFT JOIN [dbo].[TB_M_DIVISION] DIV ON DIV.DIVISION_CODE = R.DIVISION_CODE
WHERE R.DIVISION_NAME IS NULL;

UPDATE R SET
	R.DIVISION = DEP.DIVISION,
	R.DIVISION_NAME = DIVM.DIVISION_NAME,
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME
FROM [dbo].[TB_R_DOCUMENT_DISTRIBUTION] R
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT_ID
LEFT JOIN [dbo].[TB_M_DIVISION] DIVM ON DIVM.DIVISION_CODE = DEP.DIVISION
WHERE R.DIVISION_NAME IS NULL AND R.DEPARTMENT_NAME IS NULL;

UPDATE R SET
	R.DEPARTMENT_CODE = DEP.DEPARTMENT_CODE,
	R.DEPARTMENT_NAME = DEP.DEPARTMENT_NAME
FROM [dbo].[TB_R_PUBLISH_HISTORY] R
LEFT JOIN [dbo].[TB_M_DEPARTMENT] DEP ON DEP.DEPARTMENT_ID = R.DEPARTMENT_ID
WHERE R.DEPARTMENT_NAME IS NULL;
GO
